### ISSUE TITLE
log error while (re)starting

### ISSUE THREAD

**Issue by sirlinium** [GriefPrevention/GriefPrevention#115]
Dear all,

### What behaviour is expected:
no errors while starting
### What behaviour is observed:
errors whith griefprevention
### Steps/models to reproduce:
at any start or restart of our server

### Spigot/Craftbukkit/Paper and GriefPrevention version:
GriefPrevention version 16.6

### Stack trace/error (if applicable)

whole starting log:
https://pastebin.com/iDRTtZP8

the part I am interrested in:
```
[03:00:25] [INFO] [GriefPrevention] Enabling GriefPrevention v16.6
[03:00:25] [INFO] [GriefPrevention] Finished loading configuration.
[03:00:26] [INFO] [GriefPrevention] 17873.yml java.lang.NullPointerException
at me.ryanhamshire.GriefPrevention.DataStore.locationFromString(DataStore.java:469)
at me.ryanhamshire.GriefPrevention.FlatFileDataStore.loadClaim(FlatFileDataStore.java:482)
at me.ryanhamshire.GriefPrevention.FlatFileDataStore.loadClaim(FlatFileDataStore.java:472)
at me.ryanhamshire.GriefPrevention.FlatFileDataStore.loadClaimData(FlatFileDataStore.java:423)
at me.ryanhamshire.GriefPrevention.FlatFileDataStore.initialize(FlatFileDataStore.java:202)
at me.ryanhamshire.GriefPrevention.FlatFileDataStore.(FlatFileDataStore.java:53)
at me.ryanhamshire.GriefPrevention.GriefPrevention.onEnable(GriefPrevention.java:301)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378)
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328)
at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437)
at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398)
at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336)
at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276)
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603)
at java.lang.Thread.run(Thread.java:745)
[03:00:27] [INFO] [GriefPrevention] 14628.yml java.lang.NullPointerException
at me.ryanhamshire.GriefPrevention.DataStore.locationFromString(DataStore.java:469)
at me.ryanhamshire.GriefPrevention.FlatFileDataStore.loadClaim(FlatFileDataStore.java:482)
at me.ryanhamshire.GriefPrevention.FlatFileDataStore.loadClaim(FlatFileDataStore.java:472)
at me.ryanhamshire.GriefPrevention.FlatFileDataStore.loadClaimData(FlatFileDataStore.java:423)
at me.ryanhamshire.GriefPrevention.FlatFileDataStore.initialize(FlatFileDataStore.java:202)
at me.ryanhamshire.GriefPrevention.FlatFileDataStore.(FlatFileDataStore.java:53)
at me.ryanhamshire.GriefPrevention.GriefPrevention.onEnable(GriefPrevention.java:301)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378)
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328)
at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437)
at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398)
at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336)
at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276)
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603)
at java.lang.Thread.run(Thread.java:745)
[03:00:27] [INFO] [GriefPrevention] 3576 total claims loaded.
[03:00:27] [INFO] [GriefPrevention] Customizable messages loaded.
[03:00:27] [INFO] [GriefPrevention] Successfully hooked into WorldGuard.
[03:00:27] [INFO] [GriefPrevention] Finished loading data (File Mode).
[03:00:27] [INFO] [GriefPrevention] Boot finished.
```

### GriefPrevention config.yml (if applicable)

```
https://pastebin.com/e4sy2rTm
```

### Plugin list (if applicable):
Plugins (12): CoreProtect, PermissionsEx, WorldEdit, Vault, XRayHunter, WorldGuard, Multiverse-Core, Multiverse-Portals, Essentials, EssentialsSpawn, GriefPrevention, EssentialsChat

Thank you for your help !

**Comment by bigpresh** [comment]
The errors were while loading two claim data files, `17873.yml` and `14628.yml`.

Perhaps those files are empty or corrupted?  (I've seen that happen if the server ran out of disk space...)

What do the contents of those files (found in `plugins/GriefPreventionData/ClaimData/`) look like?

**Comment by sirlinium** [comment]
You are right ! those files are empty, just have to delete them ?

**Comment by RoboMWM** [comment]
Yea, might have been leftovers from when your hard disk ran out of space I bet.

**Comment by bigpresh** [comment]
Yep, if they're empty the details on the claims is gone anyway, so unless you can restore those files from your backups, just delete them, and the errors in your logs will go away :)
