### ISSUE TITLE
Plugin doesnt load

### ISSUE THREAD

**Issue by crackedpotato007** [GriefPrevention/GriefPrevention#1216]
### What happened:
_What you saw_

### What was expected:
_What you expected to see_

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
Start the server

### Server and GriefPrevention version:
PLugin doesnt load
1.15 papermc

### Stack trace/error or server log

```
07:07:17 ERROR]: Could not load 'plugins/GriefPrevention.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.16
at org.bukkit.craftbukkit.v1_15_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:276) ~[patched_1.15.2.jar:git-Paper-391]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.15.2.jar:git-Paper-391]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-391]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-391]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-391]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-391]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-391]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```
Or, paste the server.log at gist.github.com and paste the link here:

**Comment by crackedpotato007** [comment]
[07:11:16 INFO]: This server is running Paper version git-Paper-391 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by bigpresh** [comment]
What GriefPrevention version are you trying to use?

You need [16.13.0](https://github.com/TechFortress/GriefPrevention/releases/tag/16.13.0) for a 1.15.x server.

**Comment by Jikoo** [comment]
You need to downgrade GP to use it on an outdated server. The last release for 1.15 is [16.13](https://github.com/TechFortress/GriefPrevention/releases/tag/16.13.0).
