### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by DesiVb** [GriefPrevention/GriefPrevention#1359]
[10:39:09] [Server thread/ERROR]: [CS-CoreLib2] An Error occured while querying the Protection Module: "GriefPrevention v16.17.1-2b69191"
java.lang.LinkageError: loader constraint violation: loader org.bukkit.plugin.java.PluginClassLoader @7b5ae303 wants to load abstract class me.ryanhamshire.GriefPrevention.DataStore. A different abstract class with the same name was previously loaded by org.bukkit.plugin.java.PluginClassLoader @24d64f25. (me.ryanhamshire.GriefPrevention.DataStore is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @24d64f25, parent loader 'app')
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.modules.GriefPreventionProtectionModule.hasPermission(GriefPreventionProtectionModule.java:35) ~[?:?]
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.ProtectionManager.hasPermission(ProtectionManager.java:183) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.tools.GoldPan.lambda$getItemHandler$0(GoldPan.java:129) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.lambda$rightClickItem$0(SlimefunItemInteractListener.java:99) ~[?:?]
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem.callItemHandler(SlimefunItem.java:953) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.rightClickItem(SlimefunItemInteractListener.java:99) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.onRightClick(SlimefunItemInteractListener.java:67) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1122.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:611) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:534) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1829) ~[?:git-Yatopia-ver/1.16.5-100]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:32) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:10) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1346) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1315) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1155) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-100]
	at java.lang.Thread.run(Thread.java:829) [?:?]p')

I have 2 plugins that are giving me problems with the I have problems with the "gp".
SmoothTimber 1.15.0
Slimefun4 - DEV 890 (git a8e84)

it seems to throw the same errors for both, but in different ways
version del servidor: Yatopia 1.16.5-R0.1-SNAPCHOT
Ram: 16gb

**Comment by bigpresh** [comment]
I don't think this is a GP bug.  Something is trying to load the class `me.ryanhamshire.GriefPrevention.DataStore` multiple times.

You've deleted the issue template which asks for various things which could help us to help you, but one question that stands out - do you have problems with GP without "SmoothTimber" or "Slimefun4" loaded?

Maybe Yatopia does something different to how Spigot does stuff - it's a frankenfork of sorts, I don't think we've actively tested GP on it (but, as long as it's Spigot-compatible, it *should* work...)

**Comment by RoboMWM** [comment]
yea, follow the template. Info like "ram" is not very useful here.

**Comment by Jikoo** [comment]
Closing due to lack of response. Likely another plugin shading GP's files into itself for a hook, then erroring out if GP loads before it.
