### ISSUE TITLE
Outdated Worldguard prevents claiming

### ISSUE THREAD

**Issue by PureLove-X** [GriefPrevention/GriefPrevention#147]
### What behaviour is expected:
_The Ability to Claim_
### What behaviour is observed:
_When Claiming with a shovel It lets you claim with the first but not the second, when claiming with /claim it gives you a command error_
### Steps/models to reproduce:
_Do /Claim? I think this might be a me issue but I've looked through everything and can't really seem to find a fix for it._

### Spigot/Craftbukkit/Paper and GriefPrevention version:
___16.7.1___

### Stack trace/error (if applicable)

```
12.06 23:14:34 [Server] ERROR null
12.06 23:14:34 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'claim' in plugin GriefPrevention v16.7.1
12.06 23:14:34 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 23:14:34 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 23:14:34 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 23:14:34 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 23:14:34 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 23:14:34 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 23:14:34 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 23:14:34 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 23:14:34 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
12.06 23:14:34 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
12.06 23:14:34 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 23:14:34 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 23:14:34 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 23:14:34 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 23:14:34 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 23:14:34 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
12.06 23:14:34 [Server] INFO Caused by: java.lang.NullPointerException
12.06 23:14:34 [Server] INFO at com.sk89q.worldguard.bukkit.WorldConfiguration.getBoolean(WorldConfiguration.java:219) ~[?:?]
12.06 23:14:34 [Server] INFO at com.sk89q.worldguard.bukkit.WorldConfiguration.loadConfiguration(WorldConfiguration.java:344) ~[?:?]
12.06 23:14:34 [Server] INFO at com.sk89q.worldguard.bukkit.WorldConfiguration.<init>(WorldConfiguration.java:211) ~[?:?]
12.06 23:14:34 [Server] INFO at com.sk89q.worldguard.bukkit.ConfigurationManager.get(ConfigurationManager.java:228) ~[?:?]
12.06 23:14:34 [Server] INFO at com.sk89q.worldguard.bukkit.WorldGuardPlugin.hasPermission(WorldGuardPlugin.java:508) ~[?:?]
12.06 23:14:34 [Server] INFO at com.sk89q.worldguard.bukkit.permission.AbstractPermissionModel.hasPluginPermission(AbstractPermissionModel.java:45) ~[?:?]
12.06 23:14:34 [Server] INFO at com.sk89q.worldguard.bukkit.permission.RegionPermissionModel.mayIgnoreRegionProtection(RegionPermissionModel.java:42) ~[?:?]
12.06 23:14:34 [Server] INFO at me.ryanhamshire.GriefPrevention.WorldGuardWrapper.canBuild(WorldGuardWrapper.java:29) ~[?:?]
12.06 23:14:34 [Server] INFO at me.ryanhamshire.GriefPrevention.DataStore.createClaim(DataStore.java:845) ~[?:?]
12.06 23:14:34 [Server] INFO at me.ryanhamshire.GriefPrevention.GriefPrevention.onCommand(GriefPrevention.java:1071) ~[?:?]
12.06 23:14:34 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
12.06 23:14:34 [Server] INFO ... 15 more
```

### Plugin list (if applicable):
(I am Already sorry for this long list)
MCDiscordIntegrator, GroupManager, BottomLessChests, DiscordMC, TicketMaster, DurabilityWarner, CommandSpy, MultiWorld, SuperTrails, Tablist, BetterRTP, AsyncWorldEditInjector, CoreProtect, WorldEdit, EyeOnYou, OreAnnouncer, CommandBlocker, Reputation, Votifier, ProtocolLib, ImageMaps, ChatMaster, AsyncWorldEdit, ChestRestock, MysteryBox, DisableCommandsPlus, GhostBlockKiller, ServerListPlus, Vault, GAListener, Admin-Chat-Channel, Smelter, Parties, PwnFilter, HolographicDisplays, FamoustLottery, VoteParty, WorldGuard, Essentials, MarriageMaster, LiteBans, Statscraft, SilkSpawners, EssentialsChat, AuctionGUIPlus, AncientGates, GriefPrevention, EnjinMinecraftPlugin, ChestShop, EssentialsSpawn, PvPManager, Statz, Autorank, Signs, BossShopPro, LimitedUses, PlayerShops

**Comment by PureLove-X** [comment]
Update, This is actually an Error with Worldguard, (Which you can see from the log) It actually gave me a different log when I ran the command again to post it here xD So I fixed my issue by removing the world guard plugin for now, I'm not really sure what side is causing the issue though... So I'm leaving the post because the information is still nice.

**Comment by RoboMWM** [comment]
Yea, apparently I've been told that updating WorldGuard fixes this. Likely has to do with it enabling, then promptly disabling because the older version uses a deprecated config API no longer existing in 1.12 builds. But since it is loaded - GP assumes that it's enabled and functional, when it actually is not.

Let me know if updating WorldGuard fixes the issue.

**Comment by PureLove-X** [comment]
This has been fixed sorry about the no response, My computer was out for a few days. Thanks for the help.
