### ISSUE TITLE
y out of range (expected 0-256, got -3)

### ISSUE THREAD

**Issue by x1p** [GriefPrevention/GriefPrevention#1501]
### What happened:
_What you saw_
Error on console
The error probably comes from the config entry `ExtendIntoGroundDistance`. I use a high value as I want claims to be from bedrock to build-limit. This used to work just fine.

### What was expected:
_What you expected to see_
No error

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Start test server with flat world and default griefprevention (latest build 16.17.1-25-g6382a9f)
2. Make a claim (on a very low Y level, or increase ExtendIntoGroundDistance)
3. Profit!

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: [23:09:13 INFO]: This server is running Paper version git-Paper-138 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 7a5025d)
Paste of `/version GriefPrevention`:  GriefPrevention version 16.17.1-25-g6382a9f

### Stack trace/error or server log

```
[23:08:45 WARN]: [GriefPrevention] Plugin GriefPrevention v16.17.1-25-g6382a9f generated an exception while executing task 3048
java.lang.IllegalArgumentException: y out of range (expected 0-256, got -7)
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:399) ~[patched_1.17.1.jar:git-Paper-138]
at org.bukkit.craftbukkit.v1_17_R1.CraftChunk.validateChunkCoordinates(CraftChunk.java:353) ~[patched_1.17.1.jar:git-Paper-138]
at org.bukkit.craftbukkit.v1_17_R1.CraftChunkSnapshot.validateChunkCoordinates(CraftChunkSnapshot.java:166) ~[patched_1.17.1.jar:git-Paper-138]
at org.bukkit.craftbukkit.v1_17_R1.CraftChunkSnapshot.getBlockType(CraftChunkSnapshot.java:82) ~[patched_1.17.1.jar:git-Paper-138]
at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.getLowestBuiltY(AutoExtendClaimTask.java:55) ~[?:?]
at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.run(AutoExtendClaimTask.java:32) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-138]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-138]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-138]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]
```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml
default
```
In order to get the error use a flat world or raise the value to something higher like 10, 100, 256 or even higher (1.18)

### Debugging steps attempted

- [X] (If applicable) I attempted running the server without GriefPrevention installed
  - [X] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [X] I attempted running only GriefPrevention on the server
  - [X] Issue still occurs even if GriefPrevention is the only plugin running
- [X] I attempted testing for the issue on a new server
  - [X] Issue still occurs even after testing on a new server
- [X] I attempted testing for the issue with the vanilla client (no mods)
  - [X] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by Jikoo** [comment]
As a temp solution, increase your claim min depth to 0 in your config.
