### ISSUE TITLE
Mysql error 1.12

### ISSUE THREAD

**Issue by FrankHeijden** [GriefPrevention/GriefPrevention#158]
### What behaviour is expected:
working mysql connection on 1.12
### What behaviour is observed:
not working
### Steps/models to reproduce:
have some claims saved as flatfiles, then importing them to mysql will get this error

### Spigot/Craftbukkit/Paper and GriefPrevention version:
git-Spigot-9f26059-6aa0fa3 (MC 1.12)
GP: 16.7.1

### Stack trace/error (if applicable)
```
23.06 19:24:19 [Server] INFO [GriefPrevention] Enabling GriefPrevention v16.7.1
23.06 19:24:19 [Server] INFO [GriefPrevention] Finished loading configuration.
23.06 19:24:19 [Server] WARN Fri Jun 23 19:24:19 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
23.06 19:24:20 [Multicraft] Skipped 5 lines due to rate limit (30/s)
23.06 19:24:20 [Server] INFO [GriefPrevention] Customizable messages loaded.
23.06 19:24:20 [Server] INFO [GriefPrevention] Successfully hooked into WorldGuard.
23.06 19:24:21 [Server] INFO [GriefPrevention] Because there was a problem with the database, GriefPrevention will not function properly.  Either update the database config settings resolve the issue, or delete those lines from your config.yml so that GriefPrevention can use the file system to store data.
23.06 19:24:21 [Server] WARN java.lang.IllegalArgumentException: Invalid UUID string: .listing
23.06 19:24:21 [Server] WARN at java.util.UUID.fromString(UUID.java:194)
23.06 19:24:21 [Server] WARN at me.ryanhamshire.GriefPrevention.FlatFileDataStore.migrateData(FlatFileDataStore.java:821)
23.06 19:24:21 [Server] WARN at me.ryanhamshire.GriefPrevention.GriefPrevention.onEnable(GriefPrevention.java:272)
23.06 19:24:21 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
23.06 19:24:21 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
23.06 19:24:21 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
23.06 19:24:21 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
23.06 19:24:21 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
23.06 19:24:21 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
23.06 19:24:21 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
23.06 19:24:21 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
23.06 19:24:21 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
23.06 19:24:21 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
23.06 19:24:21 [Server] WARN at java.lang.Thread.run(Thread.java:748)
23.06 19:24:21 [Server] INFO [GriefPrevention] Disabling GriefPrevention v16.7.1
23.06 19:24:21 [Server] INFO [GriefPrevention] GriefPrevention disabled.
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here
```

**Comment by RoboMWM** [comment]
Please provide the server log which contains the migration process.

**Comment by FrankHeijden** [comment]
https://pastebin.com/raw/0HAetuHm

**Comment by RoboMWM** [comment]
So, this is the first time you ran the server via MySQL?

Anyways, my guess is that you have a corrupted file... Not that I recommend migrating to MySQL anyway, but I'll try to see if I can add more logging of errors in the next release...

**Comment by RoboMWM** [comment]
@FrankHeijden actually, it looks like you might have some invalid files in your playerdata folder. `.listing` is likely a hidden file on a linux system. Please delete this file.

**Comment by FrankHeijden** [comment]
Yes “.listing” was causing it, but yet there came up another issue, the spare claimblocks (cb which users had left) didnt transfer, so everyone had 0 cb left

Everything is fine now, i switched back with a backup to flatfile

**Comment by RoboMWM** [comment]
Yea, no idea there. Though neither I nor Big_Scary recommend using MySQL.
