### ISSUE TITLE
Could not pass event PlayerJoinEvent to GriefPrevention 15.3 / NoSuchMethodError

### ISSUE THREAD

**Issue by klugemonkey** [GriefPrevention/GriefPrevention#16]
BUILD:

git-Spigot-570526c-c1b529e (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

CONSOLE:

[01:10:09 ERROR]: Could not pass event PlayerJoinEvent to GriefPrevention v15.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.PlayerList.onPlayerJoin(PlayerList.java:333) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.PlayerList.a(PlayerList.java:159) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.LoginListener.b(LoginListener.java:144) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.LoginListener.E_(LoginListener.java:54) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:827) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.setPortalCooldown(I)V
        at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerJoin(PlayerEventHandler.java:766) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        ... 14 more

**Comment by RoboMWM** [comment]
#How2readupdatenotes

(Please read the update notes)
