### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by AdamDAuria** [GriefPrevention/GriefPrevention#1611]
### What happened:
Because string is null

### What was expected:
not at all. console  spam

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. in 1.17.1 
2. java 16

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 1.17.1
Paste of `/version GriefPrevention`: 16.17.1

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.
[00:04:03] [Server thread/INFO]: [GriefPrevention] 4736.yml java.lang.NullPointerException: Cannot invoke "String.split(String)" because "string" is null
    at GriefPrevention.jar//me.ryanhamshire.GriefPrevention.DataStore.locationFromString(DataStore.java:537)
    at GriefPrevention.jar//me.ryanhamshire.GriefPrevention.FlatFileDataStore.loadClaim(FlatFileDataStore.java:493)
    at GriefPrevention.jar//me.ryanhamshire.GriefPrevention.FlatFileDataStore.loadClaim(FlatFileDataStore.java:483)
    at GriefPrevention.jar//me.ryanhamshire.GriefPrevention.FlatFileDataStore.loadClaimData(FlatFileDataStore.java:434)
    at GriefPrevention.jar//me.ryanhamshire.GriefPrevention.FlatFileDataStore.initialize(FlatFileDataStore.java:212)
    at GriefPrevention.jar//me.ryanhamshire.GriefPrevention.FlatFileDataStore.<init>(FlatFileDataStore.java:64)
    at GriefPrevention.jar//me.ryanhamshire.GriefPrevention.GriefPrevention.onEnable(GriefPrevention.java:318)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535)
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449)
    at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1212)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
    at java.base/java.lang.Thread.run(Thread.java:831)

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_nether: Survival
      world_the_end: Disabled
      world: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 500
    Max Accrued Claim Blocks:
      Default: 5500
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 5
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 50
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 30
      AllClaims:
        DaysInactive: 30
        ExceptWhenOwnerHasTotalClaimBlocks: 10000000
        ExceptWhenOwnerHasBonusClaimBlocks: 50000000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 0
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false


Paste the config.yml right here inside these backticks. Please do not use a paste service for this.




### Plugin list (if applicable):

![2021-10-05_02 22 22](https://user-images.githubusercontent.com/87257360/135996582-e372cab0-b363-4dd4-a932-66f46efba885.png)


![2021-10-05_02 22 23](https://user-images.githubusercontent.com/87257360/135996623-5f4c7020-66ca-4129-84e9-34491ab64035.png)

### Debugging steps attempted
<!--These will be checkboxes you can click after creating the issue)-->
- [ NA] (If applicable) I attempted running the server without GriefPrevention installed
  - [NA ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [NA ] I attempted running only GriefPrevention on the server
  - [NA ] Issue still occurs even if GriefPrevention is the only plugin running
- [NA ] I attempted testing for the issue on a new server
  - [NA ] Issue still occurs even after testing on a new server
- [ NA] I attempted testing for the issue with the vanilla client (no mods)
  - [ NA] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by bigpresh** [comment]
Sounds like you have a corrupt/empty claim file.

What does the file `plugins/GriefPreventionData/ClaimData/4736.yml` look like?  If it is empty or corrupt, restore a copy from a backup if you need the claim to still exist, or just deleting it should make the error go away, at the cost of losing the claim - but that claim is not being loaded anyway at present.

Have you run out of disk space recently?  I have in the past seen issues where a server ran out of disk space and new claim data files could be created but not written to because of the lack of space, that would explain this.

**Comment by AdamDAuria** [comment]
ok tthx
