### ISSUE TITLE
Unhandled exception executing command 'claimbook' in plugin GriefPrevention v15.3

### ISSUE THREAD

**Issue by Sturm-FalkeRDA** [GriefPrevention/GriefPrevention#17]
Unhandled exception executing command 'claimbook' in plugin GriefPrevention v15.3

org.bukkit.command.CommandException: Unhandled exception executing command 'claimbook' in plugin GriefPrevention v15.3

 issued server command: /deleteclaim

org.bukkit.command.CommandException: Unhandled exception executing command 'deleteclaim' in plugin GriefPrevention v15.3
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.2.jar:git-Spigot-f630541-a625e45]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10.2.jar:git-Spigot-f630541-a625e45]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.2.jar:git-Spigot-f630541-a625e45]
at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.2.jar:git-Spigot-f630541-a625e45]
at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.2.jar:git-Spigot-f630541-a625e45]
at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-f630541-a625e45]
at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-f630541-a625e45]
at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-f630541-a625e45]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_80]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_80]
at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-f630541-a625e45]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot-1.10.2.jar:git-Spigot-f630541-a625e45]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.2.jar:git-Spigot-f630541-a625e45]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot-1.10.2.jar:git-Spigot-f630541-a625e45]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot-1.10.2.jar:git-Spigot-f630541-a625e45]
at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
Caused by: java.lang.NullPointerException
at me.ryanhamshire.GriefPrevention.GriefPrevention.onCommand(GriefPrevention.java:1867) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.2.jar:git-Spigot-f630541-a625e45]
... 15 more
Literally all GriefPrevention commands outside of help doesn't work.
New server, first time using plugin. What am I doing wrong?

This server is running CraftBukkit version git-Spigot-f630541-a625e45 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
[23:26:29 INFO]: You are 49 version(s) behind

**Comment by RoboMWM** [comment]
> issued server command: /deleteclaim

Um, what happened, did you paste this incorrectly?

**Comment by RoboMWM** [comment]
Yea, you definitely pasted this wrong, as this is a stacktrace for `/deleteclaim` not `/claimbook`. Only way that [line 1867](https://github.com/TechFortress/GriefPrevention/blob/b07b8a678a7a80123c35c395e8ee64ba899a7927/src/me/ryanhamshire/GriefPrevention/GriefPrevention.java#L1867) could throw a NPE is if the player somehow has a null location (perhaps you reloaded the plugin)?

I also bet it didn't load properly at startup. So yea, check the beginning of your logs when the server is starting up. And if my guessing is correct, you probably have some other plugins erroring out on startup too.

**Comment by Sturm-FalkeRDA** [comment]
Woah, my bad! super late when posting that. I also went over the logs and checked at the start of the server; grief prevention is erroring. I would assume it's some sort of conflict, but... 

http://pastebin.com/kBML5kV7

**EDIT** Switched to Java8, GriefProtection was able to generate config and load. I take it GriefProtection is compiled with JRE8? I didn't see it listed as a requirement. If so, my bad!
The server is also reporting 49 versions behind the latest spigot release; should I inform my host provider to run Buildtools again?

**Comment by RoboMWM** [comment]
>  I take it GriefProtection is compiled with JRE8? I didn't see it listed as a requirement. If so, my bad!

I did mention that if server owners are using Java 7, let me know if it is working or not on the first version I pushed out. I'm assuming that Java 7 and Java 8 have slightly different versions of the concurrentHashMap - and apparently because I'm compiling with the Java 8 SDK (despite [specifying Java 6 in the pom](https://github.com/TechFortress/GriefPrevention/blob/master/pom.xml#L12)), it's using the newer concurrentHashMap implementation.

It's highly recommended you remain on Java 8/move away from Java 7 since it is EOL.

**Comment by RoboMWM** [comment]
Phooey - if I want to compile a Java 6/7 compatible build, I'm going to have to install JDK 7... http://stackoverflow.com/questions/25705259/undefined-reference-concurrenthashmap-keyset-when-building-in-java-8?noredirect=1&lq=1

**Comment by RoboMWM** [comment]
Add a warning in commit https://github.com/TechFortress/GriefPrevention/commit/7af3d37675d25d2d6d4ff36b915114ae281fffa6 and uploaded a Java 7 version in releases.

**Comment by Sturm-FalkeRDA** [comment]
Thank you!
I'll continue to use Java 8 as well.
