### ISSUE TITLE
Could Not load The plugin

### ISSUE THREAD

**Issue by razincp** [GriefPrevention/GriefPrevention#1861]
### Observed Behavior

Could Not load The plugin

### Expected Behavior

Could Not load The plugin

### Reproduction steps

/

### Stack trace or error log

```shell
[11:54:30 ERROR]: Could not load 'plugins/GriefPrevention-Snapshot.jar' in folder 'plugins
```

### Server version

```shell
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 16.0.1+9-Ubuntu-120.04, mixed mode, sharing)
System Info: Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9-Ubuntu-120.04) Host: Linux 5.13.0-1017-azure (amd64)
```

### GriefPrevention version

```shell
Latest
```

### Configuration

```yaml
___ _            _   _             ___                      
/ __| |_ __ _ _ _| |_(_)_ _  __ _  / __| ___ _ ___ _____ _ _ 
\__ \  _/ _` | '_|  _| | ' \/ _` | \__ \/ -_) '_\ V / -_) '_|
|___/\__\__,_|_|  \__|_|_||_\__, | |___/\___|_|  \_/\___|_|  
                            |___/                            
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 16.0.1+9-Ubuntu-120.04, mixed mode, sharing)
System Info: Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9-Ubuntu-120.04) Host: Linux 5.13.0-1017-azure (amd64)
Loading libraries, please wait...
[11:54:06 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:54:07 INFO]: Reloading ResourceManager: Default, bukkit
[11:54:09 INFO]: Loaded 7 recipes
[11:54:12 INFO]: Starting minecraft server version 1.16.5
[11:54:12 INFO]: Loading properties
[11:54:12 INFO]: This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[11:54:12 WARN]: Couldn't load server icon
java.lang.IllegalArgumentException: Must be 64 pixels wide
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadServerIcon0(CraftServer.java:2074) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadServerIcon0(CraftServer.java:2062) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadIcon(CraftServer.java:1010) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.<init>(CraftServer.java:351) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerList.<init>(PlayerList.java:162) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedPlayerList.<init>(DedicatedPlayerList.java:16) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:197) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[11:54:13 INFO]: Debug logging is disabled
[11:54:13 INFO]: Server Ping Player Sample Count: 12
[11:54:13 INFO]: Using 4 threads for Netty based IO
[11:54:13 INFO]: Default game type: SURVIVAL
[11:54:13 INFO]: Generating keypair
[11:54:13 INFO]: Starting Minecraft server on 0.0.0.0:41332
[11:54:13 INFO]: Using epoll channel type
[11:54:15 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[11:54:27 WARN]: Legacy plugin SimpleTpa v5.9 does not specify an api-version.
[11:54:28 WARN]: Legacy plugin LoginSecurity v3.0.2 does not specify an api-version.
[11:54:28 WARN]: Legacy plugin EasyRanks v1.3.2 does not specify an api-version.
[11:54:30 ERROR]: Could not load 'plugins/GriefPrevention.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.17
        at org.bukkit.craftbukkit.v1_16_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:361) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[11:54:30 INFO]: [SimpleTpa] Loading SimpleTpa v5.9
[11:54:30 INFO]: [Hibernate] Loading Hibernate v2.0.0
[11:54:30 INFO]: [Citizens] Loading Citizens v2.0.24-SNAPSHOT (build 1605)
[11:54:30 INFO]: [LoginSecurity] Loading LoginSecurity v3.0.2
[11:54:30 INFO]: [sleep-most] Loading sleep-most v4.14.0
[11:54:30 INFO]: [ViaVersion] Loading ViaVersion v4.2.1
[11:54:30 INFO]: [ViaVersion] ViaVersion 4.2.1 is now loaded, injecting!
[11:54:31 INFO]: [ViaVersion] Loading 1.12 -> 1.13 mappings...
[11:54:31 INFO]: [ViaVersion] Loading 1.13 -> 1.13.2 mappings...
[11:54:31 INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 mappings...
[11:54:32 INFO]: [ViaVersion] Loading 1.14 -> 1.15 mappings...
[11:54:32 INFO]: [ViaVersion] Loading block connection mappings ...
[11:54:32 INFO]: [ViaVersion] Loading 1.15 -> 1.16 mappings...
[11:54:32 INFO]: [ViaVersion] Loading 1.16 -> 1.16.2 mappings...
[11:54:32 INFO]: [ViaVersion] Loading 1.16.2 -> 1.17 mappings...
[11:54:33 INFO]: [ViaVersion] Loading 1.17 -> 1.18 mappings...
[11:54:33 INFO]: [EasyRanks] Loading EasyRanks v1.3.2
[11:54:33 INFO]: [floodgate] Loading floodgate v2.1.0-SNAPSHOT
[11:54:35 INFO]: [floodgate] Took 2,553ms to boot Floodgate
[11:54:35 INFO]: [ViaBackwards] Loading ViaBackwards v4.2.1
[11:54:35 INFO]: [ViaBackwards] Loading translations...
[11:54:36 INFO]: [ViaBackwards] Loading 1.10 -> 1.9.4 mappings...
[11:54:36 INFO]: [ViaBackwards] Loading 1.11 -> 1.10 mappings...
[11:54:36 INFO]: [ViaBackwards] Loading 1.12 -> 1.11 mappings...
[11:54:36 INFO]: [ViaBackwards] Loading 1.13 -> 1.12 mappings...
[11:54:36 INFO]: [ViaBackwards] Loading 1.13.2 -> 1.13 mappings...
[11:54:36 INFO]: [ViaBackwards] Loading 1.14 -> 1.13.2 mappings...
[11:54:37 INFO]: [ViaBackwards] Loading 1.15 -> 1.14 mappings...
[11:54:37 INFO]: [ViaBackwards] Loading 1.16 -> 1.15 mappings...
[11:54:37 INFO]: [ViaBackwards] Loading 1.16.2 -> 1.16 mappings...
[11:54:37 INFO]: [ViaBackwards] Loading 1.17 -> 1.16.2 mappings...
[11:54:37 INFO]: [ViaBackwards] Loading 1.18 -> 1.17 mappings...
[11:54:37 INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0
[11:54:40 INFO]: [Multiverse-Core] Loading Multiverse-Core v4.3.1-b861
[11:54:40 INFO]: [ViaRewind] Loading ViaRewind v2.0.2
[11:54:40 INFO]: [LuckPerms] Loading LuckPerms v5.4.15
[11:54:41 INFO]: [AntiXRay] Loading AntiXRay v1.9.0
[11:54:41 INFO]: [Essentials] Loading Essentials v2.19.4
[11:54:41 INFO]: [EssentialsChat] Loading EssentialsChat v2.19.4
[11:54:41 INFO]: [Geyser-Spigot] Loading Geyser-Spigot v2.0.3-SNAPSHOT
[11:54:41 INFO]: [DiscordSRV] Loading DiscordSRV v1.25.1
[11:54:41 INFO]: [GeyserUpdater] Loading GeyserUpdater v1.6.2
[11:54:41 INFO]: [BetterRTP] Loading BetterRTP v3.3.0
[11:54:41 INFO]: Server permissions file permissions.yml is empty, ignoring it
[11:54:41 INFO]: [ProtocolLib] Enabling ProtocolLib v4.8.0
[11:54:41 INFO]: [ProtocolLib] Started structure compiler thread.
[11:54:41 INFO]: [ViaRewind] Enabling ViaRewind v2.0.2
[11:54:42 INFO]: [LuckPerms] Enabling LuckPerms v5.4.15
[11:54:43 INFO]:         __    
[11:54:43 INFO]:   |    |__)   LuckPerms v5.4.15
[11:54:43 INFO]:   |___ |      Running on Bukkit - Paper
[11:54:43 INFO]: 
[11:54:43 INFO]: [LuckPerms] Loading configuration...
[11:54:43 INFO]: [LuckPerms] Loading storage provider... [H2]
[11:54:45 INFO]: [LuckPerms] Loading internal permission managers...
[11:54:45 INFO]: [LuckPerms] Performing initial data load...
[11:54:46 INFO]: [LuckPerms] Successfully enabled. (took 4116ms)
[11:54:46 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[11:54:46 WARN]: The server will make no attempt to authenticate usernames. Beware.
[11:54:46 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[11:54:46 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[11:54:46 INFO]: Preparing level "world"
[11:54:47 INFO]: Preparing start region for dimension minecraft:overworld
[11:54:49 INFO]: Preparing spawn area: 0%
[11:54:49 INFO]: Preparing spawn area: 0%
[11:54:49 INFO]: Preparing spawn area: 0%
[11:54:49 INFO]: Preparing spawn area: 0%
[11:54:49 INFO]: Preparing spawn area: 0%
[11:54:50 INFO]: Preparing spawn area: 0%
[11:54:50 INFO]: Preparing spawn area: 5%
[11:54:51 INFO]: Preparing spawn area: 38%
[11:54:51 INFO]: Time elapsed: 3565 ms
[11:54:51 INFO]: Preparing start region for dimension minecraft:the_nether
[11:54:51 INFO]: Time elapsed: 543 ms
[11:54:51 INFO]: Preparing start region for dimension minecraft:the_end
[11:54:52 INFO]: Time elapsed: 399 ms
[11:54:52 INFO]: [SimpleTpa] Enabling SimpleTpa v5.9*
[11:54:52 INFO]: [SimpleTpa] If you need support contact me at https://discord.gg/SZUkza9
[11:54:52 INFO]: [SimpleTpa] Simple Tpa has been enabled on version 5.9
[11:54:52 INFO]: Enabled metrics. You may opt-out by changing plugins/bStats/config.yml
[11:54:52 INFO]: [Hibernate] Enabling Hibernate v2.0.0
[11:54:52 INFO]: [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1605)
[11:54:52 INFO]: [Citizens] Could not fetch NMS field modifiers: [[modifiers.
[11:54:52 ERROR]: [Citizens] v2.0.24-SNAPSHOT (build 1605) is not compatible with Minecraft v1_16_R3 - try upgrading or downgrading Citizens. Disabling.
[11:54:52 INFO]: [Citizens] Disabling Citizens v2.0.24-SNAPSHOT (build 1605)
[11:54:52 INFO]: [LoginSecurity] Enabling LoginSecurity v3.0.2*
[11:54:53 INFO]: [LoginSecurity] Loading base translations from "en_us"
[11:54:53 INFO]: [LoginSecurity] Loading specified translations from "en_us"
[11:54:53 INFO]: [LoginSecurity] Registering commands...
[11:54:53 INFO]: [LoginSecurity] Registering listeners...
[11:54:54 INFO]: [LoginSecurity] Using 1.12+ map captcha renderer
[11:54:54 INFO]: [sleep-most] Enabling sleep-most v4.14.0
[11:54:54 INFO]: [ViaVersion] Enabling ViaVersion v4.2.1
[11:54:54 INFO]: [EasyRanks] Enabling EasyRanks v1.3.2*
[11:54:54 INFO]: [floodgate] Enabling floodgate v2.1.0-SNAPSHOT
[11:54:55 INFO]: [ViaBackwards] Enabling ViaBackwards v4.2.1
[11:54:55 INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.3.1-b861
[11:54:55 WARN]: [Multiverse-Core] "Multiverse-Core v4.3.1-b861" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[11:54:55 INFO]: [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
[11:54:58 INFO]: [Multiverse-Core] 3 - World(s) loaded.
[11:54:58 WARN]: [Multiverse-Core] Buscript failed to load! The script command will be disabled! If you would like not to see this message, use `/mv conf enablebuscript false` to disable Buscript from loading.
[11:54:58 INFO]: [Multiverse-Core] Version 4.3.1-b861 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--
[11:54:58 INFO]: [AntiXRay] Enabling AntiXRay v1.9.0
[11:55:00 INFO]: [Essentials] Enabling Essentials v2.19.4
[11:55:01 INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[11:55:01 INFO]: [Essentials] No kits found to migrate.
[11:55:02 INFO]: [Essentials] Loaded 36926 items from items.json.
[11:55:02 INFO]: [Essentials] Using locale en_US
[11:55:02 INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[11:55:02 INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[11:55:02 WARN]: [Essentials] Detected supported permissions plugin LuckPerms without Vault installed.
[11:55:02 WARN]: [Essentials] Features such as chat prefixes/suffixes and group-related functionality will not work until you install Vault.
[11:55:02 INFO]: [Essentials] Using superperms-based permissions.
[11:55:02 INFO]: [EssentialsChat] Enabling EssentialsChat v2.19.4
[11:55:02 INFO]: [EssentialsChat] Starting Metrics. Opt-out using the global bStats config.
[11:55:02 INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.0.3-SNAPSHOT
[11:55:03 INFO]: [Geyser-Spigot] Auto-loaded Floodgate key
[11:55:03 INFO]: [Geyser-Spigot] ******************************************
[11:55:03 INFO]: [Geyser-Spigot] 
[11:55:03 INFO]: [Geyser-Spigot] Loading Geyser version 2.0.3-SNAPSHOT (git-master-67f4de9)
[11:55:03 INFO]: [Geyser-Spigot] 
[11:55:03 INFO]: [Geyser-Spigot] ******************************************
[11:55:14 INFO]: [Geyser-Spigot] Loaded Floodgate key!
[11:55:14 INFO]: [Geyser-Spigot] Started Geyser on 0.0.0.0:41332
[11:55:14 INFO]: [Geyser-Spigot] Done (11.496s)! Run /geyser help for help!
[11:55:15 INFO]: [DiscordSRV] Enabling DiscordSRV v1.25.1
[11:55:15 INFO]: [GeyserUpdater] Enabling GeyserUpdater v1.6.2
[11:55:15 INFO]: [BetterRTP] Enabling BetterRTP v3.3.0
[11:55:17 ERROR]: Couldn't load server icon
java.lang.IllegalStateException: Must be 64 pixels wide
        at org.bukkit.craftbukkit.libs.org.apache.commons.lang3.Validate.validState(Validate.java:829) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1308) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1078) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[11:55:17 INFO]: Running delayed init tasks
[11:55:17 INFO]: [Essentials] Fetching version information...
[11:55:17 INFO]: [sleep-most] UPDATE FOUND: A newer version of sleep-most is available to download!
[11:55:17 INFO]: [GeyserUpdater] You are using the latest version of GeyserUpdater!
[11:55:18 INFO]: [DiscordSRV] [JDA] Login Successful!
[11:55:18 INFO]: [ViaVersion] ViaVersion detected server version: 1.16.4/5 (754)
[11:55:18 WARN]: [ViaVersion] You are running an outdated Java version, please consider updating it to at least Java 17 (your version is 16.0.1). At some point in the future, ViaVersion will no longer be compatible with this version of Java.
[11:55:18 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[11:55:18 INFO]: Done (66.423s)! For help, type "help"
container@pterodactyl~ Server marked as running...
[11:55:18 INFO]: Timings Reset
[11:55:18 INFO]: [DiscordSRV] [JDA] Connected to WebSocket
[11:55:20 INFO]: [DiscordSRV] [JDA] Finished Loading!
[11:55:20 INFO]: [DiscordSRV] Found server G:S?? SMP Season 4(923753435466182747)
[11:55:20 INFO]: [DiscordSRV] - TC:????????????????(923804417159999488)
[11:55:20 INFO]: [DiscordSRV] - TC:????????(923801805962502194)
[11:55:20 INFO]: [DiscordSRV] - TC:????????-????(924631460793704519)
[11:55:20 INFO]: [DiscordSRV] - TC:??????-??????(927019596840583229)
[11:55:20 INFO]: [DiscordSRV] - TC:?????????-????(924637019597062225)
[11:55:20 INFO]: [DiscordSRV] - TC:??????-???????(924522522320465920)
[11:55:20 INFO]: [DiscordSRV] - TC:?????????-???-???(941220101938610226)
[11:55:20 INFO]: [DiscordSRV] - TC:??????(923800696397119549)
[11:55:20 INFO]: [DiscordSRV] - TC:??????????(924521889408352296)
[11:55:20 INFO]: [DiscordSRV] - TC:???????-??(923809994766446642)
[11:55:20 INFO]: [DiscordSRV] - TC:????????????????(923754926776135700)
[11:55:20 INFO]: [DiscordSRV] - TC:????????-?????????(941987281470910504)
[11:55:20 INFO]: [DiscordSRV] - TC:????????????-??????(923927514588532828)
[11:55:20 INFO]: [DiscordSRV] - TC:?????(925405656649986088)
[11:55:20 INFO]: [DiscordSRV] - TC:??????????????(923755324761047132)
[11:55:20 INFO]: [DiscordSRV] - TC:?????????-?????(924539071475363910)
[11:55:20 INFO]: [DiscordSRV] - TC:??????????-????(923805971774595113)
[11:55:20 INFO]: [DiscordSRV] - TC:?????????????(923813654246359041)
[11:55:20 INFO]: [DiscordSRV] - TC:?????????(924663063041417247)
[11:55:20 INFO]: [DiscordSRV] - TC:??????????????-??????(924713833749172284)
[11:55:20 INFO]: [DiscordSRV] - TC:modmail-log(929216186045038632)
[11:55:20 INFO]: [DiscordSRV] - TC:verification(957623275993829507)
[11:55:20 INFO]: [DiscordSRV] - TC:?????????-????(961256526616592464)
[11:55:20 INFO]: [DiscordSRV] - TC:???????????????-????(961315459163115630)
[11:55:20 INFO]: [DiscordSRV] - TC:??????-???????(961504133305733130)
[11:55:20 INFO]: [DiscordSRV] - TC:creative-nithash-yt-2581(964053520326197258)
[11:55:20 INFO]: [DiscordSRV] Console forwarding assigned to channel TC:??????-???????(961504133305733130)
[11:55:21 INFO]: [DiscordSRV] Enabling Essentials hook
[11:55:21 INFO]: [DiscordSRV] Enabling LuckPerms hook
[11:55:22 INFO]: [DiscordSRV] DiscordSRV is up-to-date. (339e5e81da67cfe6210679af775eb66a9b5033be)
[11:55:23 WARN]: Can't keep up! Is the server overloaded? Running 6007ms or 120 ticks behind
pl
[12:03:21 INFO]: Plugins (20): AntiXRay, BetterRTP, Citizens, DiscordSRV, EasyRanks*, Essentials, EssentialsChat, floodgate, Geyser-Spigot, GeyserUpdater, Hibernate, LoginSecurity*, LuckPerms, Multiverse-Core, ProtocolLib, SimpleTpa*, sleep-most, ViaBackwards, ViaRewind, ViaVersion
```

### Plugin list

```shell
[12:03:21 INFO]: Plugins (20): AntiXRay, BetterRTP, Citizens, DiscordSRV, EasyRanks*, Essentials, EssentialsChat, floodgate, Geyser-Spigot, GeyserUpdater, Hibernate, LoginSecurity*, LuckPerms, Multiverse-Core, ProtocolLib, SimpleTpa*, sleep-most, ViaBackwards, ViaRewind, ViaVersion
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
GP 16.18 is for Minecraft 1.17 and higher. Downgrade to [16.17.1](https://github.com/TechFortress/GriefPrevention/releases/tag/16.17.1) for 1.16.5.
