### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to GriefPrevention v16.18.1

### ISSUE THREAD

**Issue by SrBedrock** [GriefPrevention/GriefPrevention#2021]
### Observed Behavior

Error sent to the console

### Expected Behavior

Do not send error message on console

### Reproduction steps

I am trying to replicate the action that causes the error, probably by attacking a tamable entity?

### Stack trace or error log

```shell
[17:29:44] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to GriefPrevention v16.18.1
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
	at java.lang.String.replace(String.java:2957) ~[?:?]
	at me.ryanhamshire.GriefPrevention.DataStore.getMessage(DataStore.java:1886) ~[GriefPrevention-16.18.1.jar:?]
	at me.ryanhamshire.GriefPrevention.EntityEventHandler.handleEntityDamageEvent(EntityEventHandler.java:1148) ~[GriefPrevention-16.18.1.jar:?]
	at me.ryanhamshire.GriefPrevention.EntityEventHandler.onEntityDamage(EntityEventHandler.java:766) ~[GriefPrevention-16.18.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor304.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1933]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:250) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1174) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1023) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:974) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1208) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2222) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1429) ~[?:?]
	at net.minecraft.world.entity.animal.Wolf.hurt(Wolf.java:460) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1354) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2235) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:2937) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2859) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1472) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	```
```


### Server version

```shell
[17:50:46 INFO]: Current: git-Purpur-1933 (MC: 1.19.3)*
Previous: git-Purpur-1916 (MC: 1.19.3)
* You are running the latest version
```
```


### GriefPrevention version

```shell
`[17:51:42 INFO]: GriefPrevention version 16.18.1`
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    recurso: -1
    evento: -1
  Claims:
    Mode:
      world_nether: Disabled
      world_the_end: Disabled
      recurso: Disabled
      world: Survival
      evento: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 1000
    Claim Blocks Accrued Per Hour:
      Default: 200
    Max Accrued Claim Blocks:
      Default: 10000000
    Accrued Idle Threshold: 1
    AccruedIdlePercent: 1
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 15
    AutomaticNewPlayerClaimsRadiusMinimum: 10
    ExtendIntoGroundDistance: 384
    MinimumWidth: 10
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      Enabled: false
      ChestClaimDays: -1
      UnusedClaimDays: -1
      AllClaims:
        DaysInactive: -1
        ExceptWhenOwnerHasTotalClaimBlocks: 10000000
        ExceptWhenOwnerHasBonusClaimBlocks: 10000000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: true
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /clan base definir;/sethome;/pwarp definir;/marry
      sethome;/tpaccept
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 1
    ChatSlashCommands: /me;/global;/g;/l;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg;/m
    WarningMessage: Diminua a quantidade de mensagens. Spammers serão banidos!
    BanOffenders: false
    BanMessage: Banido por spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 10
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      recurso: true
      evento: true
    ProtectFreshSpawns: false
    PunishLogout: false
    CombatTimeoutSeconds: -1
    AllowCombatItemDrop: true
    BlockedSlashCommands: ''
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: false
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: false
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 10000000
    ClaimBlocksPurchaseCost: 10.0
    ClaimBlocksSellValue: 8.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: false
  VisualizationAntiCheatCompatMode: false
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 5
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - ACACIA_PLANKS
    - BIRCH_PLANKS
    - BLACK_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - COBBLESTONE
    - CYAN_WOOL
    - DARK_OAK_PLANKS
    - DEAD_BUSH
    - DIRT
    - FERN
    - GLASS
    - GLASS_PANE
    - GRASS
    - GRASS_BLOCK
    - GRAVEL
    - GRAY_WOOL
    - GREEN_WOOL
    - JUNGLE_PLANKS
    - LIGHT_BLUE_WOOL
    - LIGHT_GRAY_WOOL
    - LIME_WOOL
    - MAGENTA_WOOL
    - OAK_PLANKS
    - ORANGE_WOOL
    - PINK_WOOL
    - PURPLE_WOOL
    - RED_WOOL
    - SAND
    - SNOW
    - SPRUCE_PLANKS
    - WHITE_WOOL
    - YELLOW_WOOL
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 10
    OfflinePlayer_cache_days: 160
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: false
      Suspicious Activity: false
      Administrative Activity: true
      Debug: true
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
Attacking a tameable entity whose owner has never logged in. Would have to be plugin-created, but possible.

https://github.com/TechFortress/GriefPrevention/blob/870141cd56a9a80d712c6d520e105292722a3ceb/src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java#L1147
Owner name here should follow the `someone(UUID)` format if no username is available. We may want to split `GriefPrevention#lookupPlayerName(UUID)` to add an overload for an OfflinePlayer to prevent redundant disk reads.
