### ISSUE TITLE
PlayerInteractAtEntityEvent

### ISSUE THREAD

**Issue by GRAVATATION** [GriefPrevention/GriefPrevention#2049]
### Observed Behavior

the server shows me this error dont know how to fix it and also the /claim shows me null also

### Expected Behavior

tried to edit it and nothing

### Reproduction steps

1 just the correct configuration 

### Stack trace or error log

```shell
[Server thread/ERROR]: Error occurred while enabling GriefPrevention v16.8 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/event/player/PlayerInteractAtEntityEvent
	at me.ryanhamshire.GriefPrevention.GriefPrevention.onEnable(GriefPrevention.java:341) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.57]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.57]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.57]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.57]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.57]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.player.PlayerInteractAtEntityEvent
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:440) ~[PluginClassLoader.class:1.7.10-1614.57]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.57]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_341]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_341]

 null
org.bukkit.command.CommandException: Unhandled exception executing command 'claim' in plugin GriefPrevention v16.8
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.57]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.57]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer.class:1.7.10-1614.57]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]
Caused by: java.lang.NoSuchFieldError: BEETROOT_BLOCK
	at me.ryanhamshire.GriefPrevention.Claim.<init>(Claim.java:335) ~[?:?]
	at me.ryanhamshire.GriefPrevention.Claim.<init>(Claim.java:246) ~[?:?]
	at me.ryanhamshire.GriefPrevention.DataStore.createClaim(DataStore.java:823) ~[?:?]
	at me.ryanhamshire.GriefPrevention.GriefPrevention.onCommand(GriefPrevention.java:1081) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.57]
	... 13 more
```

### Server version

```shell
Forge Mod Loader version 7.99.4.1614 for Minecraft 1.7.10 loading so using 1.12
```

### GriefPrevention version

```shell
16.9
```

### Configuration

```yaml
riefPrevention:
  SeaLevelOverrides:
    world: -1
    DIM-7: -1
    DIM-100: -1
    DIM-34: -1
    DIM-37: -1
    DIM-38: -1
    DIM-39: -1
    DIM-19: -1
    DIM-42: -1
    DIM-112: -1
    DIM-1: -1
    DIM1: -1
    DIM-6: -1
  Claims:
    Mode:
      DIM-6: Survival
      DIM-42: Survival
      DIM-39: Survival
      DIM-37: Survival
      DIM-1: Survival
      DIM-100: Survival
      DIM-38: Survival
      DIM-19: Survival
      world: Survival
      DIM1: Survival
      DIM-112: Survival
      DIM-34: Survival
      DIM-7: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 10000
    Claim Blocks Accrued Per Hour:
      Default: 50
    Max Accrued Claim Blocks:
      Default: 2000
    Accrued Idle Threshold: 1
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2000
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 5
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      DIM-7: true
      DIM-100: true
      DIM-34: true
      DIM-37: true
      DIM-38: true
      DIM-39: true
      DIM-19: true
      DIM-42: true
      DIM-112: true
      DIM-1: true
      DIM1: true
      DIM-6: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: 
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: 'no'
    UserName: 'no'
    Password: 'no'
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust: []
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Advanced:
    fixNegativeClaimblockAmounts: true
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Plugin list

```shell
clearlag
worldedit
mychat
vault
votifier
chunkloader
griefprevention
mycommand
bigbrother
essentialsx
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
GP 16.8 was compiled against 1.12. You're running some weird hybrid server on 1.7.10. You need an older GP version.

**Comment by GRAVATATION** [comment]
> GP 16.8 was compiled against 1.12. You're running some weird hybrid server on 1.7.10. You need an older GP version.

how much of older version would you suggest

**Comment by Jikoo** [comment]
https://dev.bukkit.org/projects/grief-prevention/files You can see the version files are compiled against in the list on the right. The last 1.7 file was 9.1

**Comment by GRAVATATION** [comment]
> https://dev.bukkit.org/projects/grief-prevention/files You can see the version files are compiled against in the list on the right. The last 1.7 file was 9.1

thank you very much
