### ISSUE TITLE
Could not pass event PlayerQuitEvent to GriefPrevention v16.18

### ISSUE THREAD

**Issue by buzznation** [GriefPrevention/GriefPrevention#2191]
### Observed Behavior

Players getting kicked with error "MrPinguinNL was kicked due to keepalive timeout!" followed by the console error stated below.

### Expected Behavior

player should not be kicked 

### Reproduction steps

Happens randomly

### Stack trace or error log

```shell
- [Fri 22:05:06 ERROR Minecraft] Could not pass event PlayerQuitEvent to GriefPrevention v16.18
java.lang.ClassCastException: class com.destroystokyo.paper.profile.CraftPlayerProfile cannot be cast to class org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile (com.destroystokyo.paper.profile.CraftPlayerProfile and org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile are in unnamed module of loader java.net.URLClassLoader @7aec35a)
    at org.bukkit.craftbukkit.v1_20_R1.ban.CraftProfileBanList.isBanned(CraftProfileBanList.java:79)
    at org.bukkit.craftbukkit.v1_20_R1.ban.CraftProfileBanList.isBanned(CraftProfileBanList.java:17)
    at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.isBanned(CraftPlayer.java:1631)
    at GriefPrevention.jar//me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerQuit(PlayerEventHandler.java:935)
    at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
    at net.minecraft.server.players.PlayerList.remove(PlayerList.java:599)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2123)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:533)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:483)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:407)
    at net.minecraft.network.Connection.tick(Connection.java:602)
    at net.mine
```

### Server version

```shell
[22:17:55 INFO]: Checking version, please wait...
[22:17:56 INFO]: This server is running Paper version git-Paper-71 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b3dc7a3)
```

### GriefPrevention version

```shell
[22:18:32 INFO]: GriefPrevention version 16.18
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    IridiumSkyblock: -1
    IridiumSkyblock_nether: -1
    IridiumSkyblock_the_end: -1
    world_survival: -1
    world_dungeons: -1
    world_resources: -1
    world_end: -1
  Claims:
    Mode:
      world_survival: Survival
      IridiumSkyblock_the_end: Disabled
      world_resources: Survival
      world: Disabled
      world_end: Disabled
      IridiumSkyblock: Survival
      IridiumSkyblock_nether: Disabled
      world_nether: Survival
      world_dungeons: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      IridiumSkyblock: true
      IridiumSkyblock_nether: true
      IridiumSkyblock_the_end: true
      world_survival: true
      world_dungeons: true
      world_resources: true
      world_end: true
    ProtectFreshSpawns: false
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Plugin list

```shell
[22:19:22 INFO]: Server Plugins (103):
[22:19:22 INFO]: Paper Plugins:
[22:19:22 INFO]:  - AdvancedKits, Minepacks, RoseStacker
[22:19:22 INFO]: Bukkit Plugins:
[22:19:22 INFO]:  - ACubelets, AdvancedBan, AuctionHouse, AureliumSkills, AutoPickup, BeastCore, BeastWithdraw, BuycraftX, ChestSort, Chunky
[22:19:22 INFO]:  Chunky, Citizens, CMILib, ColoredSigns, CrazyCrates, CrazyEnvoys, CustomCommands, DamageIndicator, DecentHolograms, DeluxeMenus
[22:19:22 INFO]:  DiscordEffect, DiscordSRV, DiscordSRVUtils, dynmap, eGlow, Essentials, Essentials, EvenMoreFish, ExecutableItems, FarmControl
[22:19:22 INFO]:  FlightControl, floodgate, GCore, Geyser-Spigot, GPFlags, GriefPrevention, IridiumSkyblock, ItemJoin, ItemTags, Jobs
[22:19:22 INFO]:  LibsDisguises, LuckPerms, LumberJack, MiniMOTD, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, MythicMobs, PL-Hide, PlaceholderAPI
[22:19:22 INFO]:  *Playtimes, PluginManagerPlus, PlugManX, ProtocolLib, QuickShop, RawMsg, ResourceWorld, SCore, SupremeAnnouncements, SupremeAWD
[22:19:22 INFO]:  SupremeBlackmarket, SupremeChat, SupremeClear, SupremeColor, SupremeCombat, SupremeCompleter, SupremeContainers, SupremeCore, SupremeCosmetics, SupremeCycle
[22:19:22 INFO]:  SupremeDeath, SupremeDrops, SupremeEssentials, SupremeGamble, SupremeJoin, SupremeLevels, SupremeMerchant, SupremePlayershops, SupremeQuests, SupremeRewards
[22:19:22 INFO]:  SupremeTags, SupremeTeleport, SupremeTitles, SupremeTokens, SupremeTransfer, SupremeVote, SupremeVouchers, TAB, TradeSystem, UltraSetHome
[22:19:22 INFO]:  Vault, ViaBackwards, ViaRewind, ViaVersion, VirtualBooks, Votifier, WildTools, WorldEdit, WorldGuard, WorldGuardExtraFlags
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
Update your server, this is an issue with the Paper version you're running.
