### ISSUE TITLE
PlayerPortalEvent error

### ISSUE THREAD

**Issue by FrankHeijden** [GriefPrevention/GriefPrevention#225]
### What behaviour is expected:
no error
### What behaviour is observed:
error
### Steps/models to reproduce:
at random

### Spigot/Craftbukkit/Paper and GriefPrevention version:
CraftBukkit version git-Spigot-5695bca-53fccdf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
GP 16.7.1

### Stack trace/error (if applicable)

```
11.11 21:32:12 [Server] ERROR Could not pass event PlayerPortalEvent to GriefPrevention v16.7.1
11.11 21:32:12 [Server] INFO org.bukkit.event.EventException: null
11.11 21:32:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerList.changeDimension(PlayerList.java:756) [spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO at net.minecraft.server.v1_12_R1.EntityPlayer.b(EntityPlayer.java:618) [spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO at net.minecraft.server.v1_12_R1.Entity.postTick(Entity.java:340) [spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1634) [spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO at net.minecraft.server.v1_12_R1.World.h(World.java:1603) [spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:688) [spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1405) [spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
11.11 21:32:12 [Server] INFO Caused by: java.lang.NoSuchMethodError: me.ryanhamshire.GriefPrevention.GriefPrevention.startRescueTask(Lorg/bukkit/entity/Player;)V
11.11 21:32:12 [Server] INFO at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerPortal(PlayerEventHandler.java:1000) ~[GriefPrevention.jar:?]
11.11 21:32:12 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
11.11 21:32:12 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
11.11 21:32:12 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
11.11 21:32:12 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
11.11 21:32:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-update.jar:git-Spigot-5695bca-53fccdf]
11.11 21:32:12 [Server] INFO ... 16 more
```

### GriefPrevention config.yml (if applicable)

```yml
PortalGenerationRequiresPermission: false
```

### Plugin list (if applicable):
meh

**Comment by FrankHeijden** [comment]
will test this further; on testserver with no other plugins and see what causes this.
