### ISSUE TITLE
GriefPrevention Incompatible with Graves 4.9

### ISSUE THREAD

**Issue by realBritakee** [GriefPrevention/GriefPrevention#2336]
### Observed Behavior

i started my server with GriefPrevention Latest and Graves 4.9 and it crashed instantly and i had no time to see the console cuz it instantly crashed i have other plugins but i tested them and only graves crashes the server

### Expected Behavior

The server should start lol

### Reproduction steps

1. Start a Minecraft 1.20.1 Server
2. add GriefPrevention Latest and Graves 4.9
3. Start server and see

### Stack trace or error log

```shell
[18:44:36] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:44:37] [ServerMain/INFO]: Loaded 7 recipes
[18:44:37] [Server thread/INFO]: Starting minecraft server version 1.20.1
[18:44:37] [Server thread/INFO]: Loading properties
[18:44:37] [Server thread/INFO]: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
[18:44:38] [Server thread/INFO]: Server Ping Player Sample Count: 12
[18:44:38] [Server thread/INFO]: Using 4 threads for Netty based IO
[18:44:38] [Server thread/WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[18:44:38] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 4 worker threads, and gen parallelism of 4 threads
[18:44:38] [Server thread/INFO]: Default game type: SURVIVAL
[18:44:38] [Server thread/INFO]: Generating keypair
[18:44:38] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:25565
[18:44:38] [Server thread/INFO]: Using default channel type
[18:44:38] [Server thread/INFO]: Paper: Using Java compression from Velocity.
[18:44:38] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[18:44:38] [Server thread/ERROR]: [SimpleProviderStorage] Circular plugin loading detected!
[18:44:38] [Server thread/ERROR]: [SimpleProviderStorage] Circular load order:
[18:44:38] [Server thread/ERROR]: [SimpleProviderStorage]   Skript -> GriefPrevention -> Graves -> Skript
[18:44:38] [Server thread/ERROR]: [SimpleProviderStorage]   Skript -> GriefPrevention -> Graves -> ItemsAdder -> Skript
[18:44:38] [Server thread/ERROR]: [SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.
[18:44:38] [Server thread/ERROR]: [SimpleProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
[18:44:38] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Circular plugin loading from plugins Skript, Skript
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.handleCycle(SimpleProviderStorage.java:78) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:43) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:510) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[18:44:39] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Britakee\Desktop\Server Files\.\crash-reports\crash-2024-07-20_18.44.39-server.txt
[18:44:39] [Server thread/INFO]: Stopping server
[18:44:39] [Server thread/INFO]: Saving players
[18:44:39] [Server thread/INFO]: Saving worlds
[18:44:39] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[18:44:39] [Server thread/INFO]: Flushing Chunk IO
[18:44:39] [Server thread/INFO]: Closing Thread Pool
[18:44:39] [Server thread/INFO]: Closing Server
```

### Server version

```shell
Paper 1.20.1196
```

### GriefPrevention version

```shell
Latest Build
```

### Configuration

```yaml
Dos not create one
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by RoboMWM** [comment]
Have you reported this to the graves author? We don't have any dependency or loadbefore on skript nor graves. Also, "latest version" isn't a version.

**Comment by Jikoo** [comment]
Likely a pure Graves problem, they probably have a loadbefore GriefPrevention and a soft dependency on Skript. [Skript softdepends on GriefPrevention](https://github.com/SkriptLang/Skript/blob/0e10975d55b87b742a38ed9f4b01e9cfead1269d/src/main/resources/plugin.yml#L41).

**Comment by Jikoo** [comment]
I've opened an issue on your behalf over at the active fork of Graves' repo. Please watch that for updates.
