### ISSUE TITLE
Could not pass event VehicleDamageEvent to GriefPrevention v9.1

### ISSUE THREAD

**Issue by MeSoLost** [GriefPrevention/GriefPrevention#26]
### What behaviour is expected:

Nothing (no error generated)
### What behaviour is observed:

The error
### Steps/models to reproduce:

I believe it happened underground in a mine as I was exploring and generating new terrain.  Recreate? Um... put water/lava next to a minecart?
### Spigot/Craftbukkit/Paper and GriefPrevention version:

Thermos | https://github.com/CyberdyneCC/Thermos | 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.58 (MC: 1.7.10) (Minecraft Forge Server Software implementing the Spigot/Bukkit API, formerly known as Cauldron/MCPC)
SOB! /plugins lists plugins but /version [plugin name] ALWAYS replies This server isnt running any plugins despite the fact i have 19 listed on the /plugins list so I'm stuck assuming it's version 9.1 unless your plugin lies on the console -_-
### Stack trace/error (if applicable)

```
[20:01:09] [Server thread/ERROR] [Minecraft/]: Could not pass event VehicleDamageEvent to GriefPrevention v9.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.58]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
    at net.minecraft.entity.item.EntityMinecart.func_70097_a(EntityMinecart.java:183) [xl.class:?]
    at net.minecraft.entity.Entity.func_70081_e(Entity.java:1143) [sa.class:?]
    at net.minecraft.entity.Entity.func_70091_d(Entity.java:999) [sa.class:?]
    at net.minecraft.entity.item.EntityMinecart.func_94088_b(EntityMinecart.java:520) [xl.class:?]
    at net.minecraft.entity.item.EntityMinecart.func_70071_h_(EntityMinecart.java:398) [xl.class:?]
    at net.minecraft.world.World.func_72866_a(World.java:2740) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:877) [mt.class:?]
    at net.minecraft.world.World.func_72870_g(World.java:2678) [ahb.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:2480) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
    at me.ryanhamshire.GriefPrevention.EntityEventHandler.onVehicleDamage(EntityEventHandler.java:573) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
    ... 18 more
[20:01:09] [Server thread/ERROR] [Minecraft/]: Could not pass event VehicleDamageEvent to GriefPrevention v9.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.58]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
    at net.minecraft.entity.item.EntityMinecart.func_70097_a(EntityMinecart.java:183) [xl.class:?]
    at net.minecraft.entity.Entity.func_70081_e(Entity.java:1143) [sa.class:?]
    at net.minecraft.entity.Entity.func_70091_d(Entity.java:999) [sa.class:?]
    at net.minecraft.entity.item.EntityMinecart.func_94088_b(EntityMinecart.java:520) [xl.class:?]
    at net.minecraft.entity.item.EntityMinecart.func_70071_h_(EntityMinecart.java:398) [xl.class:?]
    at net.minecraft.world.World.func_72866_a(World.java:2740) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:877) [mt.class:?]
    at net.minecraft.world.World.func_72870_g(World.java:2678) [ahb.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:2480) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
    at me.ryanhamshire.GriefPrevention.EntityEventHandler.onVehicleDamage(EntityEventHandler.java:573) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
    ... 18 more
[20:01:09] [Server thread/ERROR] [Minecraft/]: Could not pass event VehicleDamageEvent to GriefPrevention v9.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.58]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
    at net.minecraft.entity.item.EntityMinecart.func_70097_a(EntityMinecart.java:183) [xl.class:?]
    at net.minecraft.entity.Entity.func_70081_e(Entity.java:1143) [sa.class:?]
    at net.minecraft.entity.Entity.func_70091_d(Entity.java:999) [sa.class:?]
    at net.minecraft.entity.item.EntityMinecart.func_94088_b(EntityMinecart.java:520) [xl.class:?]
    at net.minecraft.entity.item.EntityMinecart.func_70071_h_(EntityMinecart.java:398) [xl.class:?]
    at net.minecraft.world.World.func_72866_a(World.java:2740) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:877) [mt.class:?]
    at net.minecraft.world.World.func_72870_g(World.java:2678) [ahb.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:2480) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
    at me.ryanhamshire.GriefPrevention.EntityEventHandler.onVehicleDamage(EntityEventHandler.java:573) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
    ... 18 more
[20:01:09] [Server thread/ERROR] [Minecraft/]: Could not pass event VehicleDamageEvent to GriefPrevention v9.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.58]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
    at net.minecraft.entity.item.EntityMinecart.func_70097_a(EntityMinecart.java:183) [xl.class:?]
    at net.minecraft.entity.Entity.func_70081_e(Entity.java:1143) [sa.class:?]
    at net.minecraft.entity.Entity.func_70091_d(Entity.java:999) [sa.class:?]
    at net.minecraft.entity.item.EntityMinecart.func_94088_b(EntityMinecart.java:520) [xl.class:?]
    at net.minecraft.entity.item.EntityMinecart.func_70071_h_(EntityMinecart.java:398) [xl.class:?]
    at net.minecraft.world.World.func_72866_a(World.java:2740) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:877) [mt.class:?]
    at net.minecraft.world.World.func_72870_g(World.java:2678) [ahb.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:2480) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
    at me.ryanhamshire.GriefPrevention.EntityEventHandler.onVehicleDamage(EntityEventHandler.java:573) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
    ... 18 more
[20:01:09] [Server thread/ERROR] [Minecraft/]: Could not pass event VehicleDamageEvent to GriefPrevention v9.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.58]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
    at net.minecraft.entity.item.EntityMinecart.func_70097_a(EntityMinecart.java:183) [xl.class:?]
    at net.minecraft.entity.Entity.func_70081_e(Entity.java:1143) [sa.class:?]
    at net.minecraft.entity.Entity.func_70091_d(Entity.java:999) [sa.class:?]
    at net.minecraft.entity.item.EntityMinecart.func_94088_b(EntityMinecart.java:520) [xl.class:?]
    at net.minecraft.entity.item.EntityMinecart.func_70071_h_(EntityMinecart.java:398) [xl.class:?]
    at net.minecraft.world.World.func_72866_a(World.java:2740) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:877) [mt.class:?]
    at net.minecraft.world.World.func_72870_g(World.java:2678) [ahb.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:2480) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
    at me.ryanhamshire.GriefPrevention.EntityEventHandler.onVehicleDamage(EntityEventHandler.java:573) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
    ... 18 more

```

[fml-server-latest.txt](https://github.com/TechFortress/GriefPrevention/files/520669/fml-server-latest.txt)

**Comment by RoboMWM** [comment]
I'm not supporting older versions, especially that ancient version. Please try to update, or find someone to fork and fix for you.

**Comment by FireController1847** [comment]
Rude af. You know, some people CAN'T update because they own a modpack that DOESN'T support the new mods yet. Amazing the owners essentially say stuff like SOL. You could have at least been more nice about it. And I understand that code between 1.7.10 and 1.8+ is extremely different but don't be an asshole and say SOL.

(Looking at this 7/20/2018 and even though it's a couple years later I thought I'd apologize anyways. You weren't rude at all and this was old me being weird lol)

**Comment by RoboMWM** [comment]
@FireController1847 

> Rude af. You know, some people CAN'T update because they own a modpack that DOESN'T support the new mods yet. Amazing the owners essentially say stuff like SOL. You could have at least been more nice about it. And I understand that code between 1.7.10 and 1.8+ is extremely different but don't be an asshole and say SOL.

I mean, how else am I supposed to make it sound nice? I didn't spout profanity or anything. I simply stated that I do not support older versions. Suggestions on how it could've sounded nicer?

**Comment by RoboMWM** [comment]
> You know, some people CAN'T update because they own a modpack that DOESN'T support the new mods yet. 

Just to comment on this specifically - this is something the owner decides to do - they could choose to update and/or ask for fixes from the modpack developer for example, or choose not to use those specific mods holding them back.

**Comment by bigpresh** [comment]
Just to add, at no point did he say you were SOL; he stated that he won't be maintaining versions that old (which is perfectly reasonable) and suggested alternative solutions to you.  It didn't sound particularly rude to me - just straight to the point.

Open source project authors do their work in their own free time, and they have zero obligation to anyone to maintain past versions, or even the latest version / the project themselves - they have to decide where they are able and willing to spend their time - and maintaining ancient versions is a big drain on time for the benefit of not many users, so I don't see anything wrong with that.

Hell, people pay Microsoft for their software, and they cut off support for old versions too - and they have a lot of developers being paid to work on their stuff as their day job!

Perhaps this was just a misunderstanding of intent thanks to the vaguaries of text-based communication?

Either way, you could talk to the modpack author and see if they're willing to consider updating it to work with newer versions, or find someone willing to update it for you, or to work on older GP versions to backport fixes etc to get it working for you.  I wish you luck, whatever route you take.
