### ISSUE TITLE
water_bucket 1.13

### ISSUE THREAD

**Issue by Promic2** [GriefPrevention/GriefPrevention#317]
[GriefPrevention] Gamer_Jokke placed suspicious WATER_BUCKET @ world: x-147, z960
[01:37:16] [Thread-14/WARN]: java.lang.NullPointerException
[01:37:16] [Thread-14/WARN]: 	at net.coreprotect.database.Logger.getItemMeta(Logger.java:105)
[01:37:16] [Thread-14/WARN]: 	at net.coreprotect.database.Logger.container_logger(Logger.java:134)
[01:37:16] [Thread-14/WARN]: 	at net.coreprotect.database.Logger.log_container(Logger.java:290)
[01:37:16] [Thread-14/WARN]: 	at net.coreprotect.consumer.Process.processContainerTransaction(Process.java:262)
[01:37:16] [Thread-14/WARN]: 	at net.coreprotect.consumer.Process.processConsumer(Process.java:99)
[01:37:16] [Thread-14/WARN]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:105)
[01:37:16] [Thread-14/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by Jikoo** [comment]
>net.coreprotect.database.Logger

This is the GriefPrevention issue tracker

**Comment by Promic2** [comment]
ohhh sorry

**Comment by bigpresh** [comment]
Yeah, that looks like CoreProtect isn't updated for 1.13 yet - CP's ticket tracker appears to be at https://dev.bukkit.org/projects/coreprotect/issues
