### ISSUE TITLE
WorldEdit and GriefPrevention incompatibility 

### ISSUE THREAD

**Issue by THENATHE** [GriefPrevention/GriefPrevention#337]
### What behaviour is observed:
___When a dev build of world edit is also installed, claims will not create, always citing there is less than 100 blocks, despite trying to make a claim that is hundreds of blocks wide and long___
### What behaviour is expected:
___The ability to make a claim.___
### Steps/models to reproduce:
__Put on a dev build of worldedit and try to claim blocks.___

### Spigot/Craftbukkit/Paper and GriefPrevention version:
___1.13 spigot beta, latest nightly build of world edit, and latest GP build published to spigot as of 8/1/18___

### Stack trace/error

```
[02:22:59] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to GriefPrevention v16.8
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:451) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1227) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot.jar:git-Spigot-69774b3-272426a]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/permission/RegionPermissionModel
	at me.ryanhamshire.GriefPrevention.WorldGuardWrapper.canBuild(WorldGuardWrapper.java:36) ~[?:?]
	at me.ryanhamshire.GriefPrevention.DataStore.createClaim(DataStore.java:863) ~[?:?]
	at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerInteract(PlayerEventHandler.java:2440) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot.jar:git-Spigot-69774b3-272426a]
	... 17 more
```

### GriefPrevention config.yml (if applicable)

```yml
NA
```

### Plugin list (if applicable):
World Edit (nightly)
World Guard (nightly)
GriefPrevention (latest as of 8/1/18)

**Comment by THENATHE** [comment]
Duplicate issue

**Comment by AeSix** [comment]
@THENATHE it'd be nice if you'd link to the duplicate issue.  I found this issue while looking for info, annnnd now I feel like I need to search the issue tracker for this duplicate issue.

**Comment by RoboMWM** [comment]
Protip: Use `/version <plugin name>` to get the plugin versions.

**Comment by RoboMWM** [comment]
@AeSix wow this is old, you made me think this was new lol. Searching the issue tracker is easy if you've found this issue. Just search in the top left corner, and then filter by issues. There are a couple of worldguard-related issues, if you don't want to make a new issue you can ask in #griefprevention on IRC.

This issue in particular is likely due to mismatched Worldguard/Worldedit version (i.e. MC 1.13 version, perhaps?)

I agree though, if you are going to close as duplicate, would be helpful to reference the old issue.

**Comment by AeSix** [comment]
Yeah, I figured it out.  This issue was literally 3rd or 4th in google results lol  

But yeah, WorldGuard 7 beta 3, WorldEdit 7 beta 5 and GP 16.11.6 works wonderfully well together on my 1.13.2 server  (for future reference if anyone else comes along and finds this issues and wants to face desk) :D

**Comment by zefir-git** [comment]
@AeSix could you mention the issue here using e.g. #337?

**Comment by RoboMWM** [comment]
@williamd5 ??? what are you referencing?

**Comment by zefir-git** [comment]
> @williamd5 ??? what are you referencing?

The mysterious duplicate issue that nobody wants to link.

Anyway, if anyone is looking for a plugin that actually is compatible with GriefPrevention and WorldGuard, try FAWE. The lack of configuration and compatibility when it comes to vanilla WorldEdit just astonishes me. If you are looking to allow players to use W/E on survival mode, the original WorldEdit **will not work** unless you want to allow players to duplicate items endlessly (with use-inventory enabled). For instance, select a diamond block and have 64 stone in your inventory. Run `//set stone`, nice now you have a diamond block in your inventory. Run `//undo`. Now the diamond block is still in your inventory so you can just `//set stone` to get another one. There's an extensive array of other bugs too and it truly makes me wonder whether the developers even test what they code. (not to mention you would expect WorldEdit to be async by now)

**Comment by RoboMWM** [comment]
Oh ok I see now. I never bothered to look but this issue was duplicated many times, and in most of those I linked to the first report. I'm on mobile rn so yes I too am again gonna fail to link the dupe. But I'll keep this in notifications to link it later if someone doesn't beat me to it.

The incompatibility here is with worldguard's breaking API changes with improperly-tagged versions (despite releasing as betas otherwise on bukkitdev...)

**Comment by RoboMWM** [comment]
Duplicate of #329
