### ISSUE TITLE
/claim and /expandclaim crashing in 16.9

### ISSUE THREAD

**Issue by tsiedsma** [GriefPrevention/GriefPrevention#352]
### What behaviour is observed:
Server crashes and restarts,   I can't find any log entries related to using /expandclaim, but the server crashes then too.
### What behaviour is expected:
...
### Steps/models to reproduce:
Stand in a claim and type /expandclaim using a goldshovel
### Spigot/Craftbukkit/Paper and GriefPrevention version:
CraftBukkit version git-Spigot-69774b3-a9c796f (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
GriefPrevention version 16.9

### Stack trace/error

```
[11:16:34] [Server thread/INFO]: DarkLotus issued server command: /claim
[11:16:34] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'claim' in plugin GriefPrevention v16.9.alpha
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_13_R1/CraftChunkSnapshot
	at org.bukkit.craftbukkit.v1_13_R1.CraftChunk.getChunkSnapshot(CraftChunk.java:217) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at me.ryanhamshire.GriefPrevention.GriefPrevention.autoExtendClaim(GriefPrevention.java:3585) ~[?:?]
	at me.ryanhamshire.GriefPrevention.GriefPrevention.onCommand(GriefPrevention.java:1101) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	... 15 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_13_R1.CraftChunkSnapshot
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	at org.bukkit.craftbukkit.v1_13_R1.CraftChunk.getChunkSnapshot(CraftChunk.java:217) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at me.ryanhamshire.GriefPrevention.GriefPrevention.autoExtendClaim(GriefPrevention.java:3585) ~[?:?]
	at me.ryanhamshire.GriefPrevention.GriefPrevention.onCommand(GriefPrevention.java:1101) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	... 15 more
[11:16:34] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Error generating crash report
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:947) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R1/CrashReportCallable
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:945) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	... 4 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R1.CrashReportCallable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:945) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	... 4 more
[11:16:34] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R1/CrashReportCallable
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:945) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) ~[spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-1503de9-4487c1f]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R1.CrashReportCallable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	... 5 more
[11:16:34] [Server thread/INFO]: Stopping server
```

### GriefPrevention config.yml (if applicable)

```yml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world: Survival
      world_nether: Disabled
      world_the_end: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 3000
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 30000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 10
    ExtendIntoGroundDistance: 100
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 14
      UnusedClaimDays: 180
      AllClaims:
        DaysInactive: -1
        ExceptWhenOwnerHasTotalClaimBlocks: 0
        ExceptWhenOwnerHasBonusClaimBlocks: 0
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome;/tpahere
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa;/back
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: false
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: false
  AdminsGetSignNotifications: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
  EndermenMoveBlocks: true
  SilverfishBreakBlocks: true
  CreaturesTrampleCrops: true
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: true
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Advanced:
    fixNegativeClaimblockAmounts: true
  Abridged Logs:
    Days To Keep: 365
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: true
      Muted Chat Messages: true
```
### Plugin list (if applicable):
EssentialsX version: 2.15.0.18
PermissionsEx version: 1.23.4
Vault version: 1.5.6-b49
EssentialsXChat version: 2.15.0.18
EssentialsXSpawn version: 2.15.0.18

**Comment by NullCase** [comment]
try GOLDEN_SPADE or try regenerating your config.

Its functioning correctly for me. I don't have PermissionsEx. And i'm on Vault 1.6.6.

**Comment by tsiedsma** [comment]
Ahh, good catch, I'll give it a try

**Comment by tsiedsma** [comment]
Ok, that worked, sorry for the false alarm!
