### ISSUE TITLE
Cannot use GriefPrevention

### ISSUE THREAD

**Issue by Grumpy-Gordon** [GriefPrevention/GriefPrevention#359]
### What behaviour is observed:
Unable to use the plugin, use of the shovel to claim, doesn't complete the claim creation.
Trying to claim with a chest also has no effect.
(also the same with adminclaims)
### What behaviour is expected:
A claim to be created upon the second right click
### Steps/models to reproduce:
Try and create a claim, which you can afford (If it isn't affordable, it will give the 'normal' errormessage. 

### Spigot/Craftbukkit/Paper and GriefPrevention version:

This server is running CraftBukkit version git-Spigot-fe3ab0d-3418f8d (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

GriefPrevention version 16.8

### Stack trace/error

```
[15:18:12 ERROR]: Could not pass event PlayerInteractEvent to GriefPrevention v16.8
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-latest.jar:git-Spigot-fe3ab0d-3418f8d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-latest.jar:git-Spigot-fe3ab0d-3418f8d]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-latest.jar:git-Spigot-fe3ab0d-3418f8d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-latest.jar:git-Spigot-fe3ab0d-3418f8d]
        at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238) ~[spigot-latest.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:452) ~[spigot-latest.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1227) ~[spigot-latest.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-latest.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-latest.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-latest.jar:git-Spigot-fe3ab0d-3418f8d]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-latest.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-latest.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-latest.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-latest.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-latest.jar:git-Spigot-fe3ab0d-3418f8d]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/permission/RegionPermissionModel
        at me.ryanhamshire.GriefPrevention.WorldGuardWrapper.canBuild(WorldGuardWrapper.java:36) ~[?:?]
        at me.ryanhamshire.GriefPrevention.DataStore.createClaim(DataStore.java:863) ~[?:?]
        at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerInteract(PlayerEventHandler.java:2440) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-latest.jar:git-Spigot-fe3ab0d-3418f8d]
```

### GriefPrevention config.yml (if applicable)

```yml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_nether: Disabled
      world: Survival
      world_the_end: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 2000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust: []
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Advanced:
    fixNegativeClaimblockAmounts: true
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

Essentials X- 2.15.0.1
Essentials X Chat- 2.15.0.1
Essentials X GeoIP- 2.15.0.1
Essentials X Protect- 2.15.0.1
Essentials X Spawn- 2.15.0.1
FAWE -bukkit-18.08.22-9927cde-2017
GriefPrevention
LuckPerms-Bukkit-42.58
Vault
Worldguard Legacy-7.0.0-Snapshot-dist
```

**Comment by Dogeveloper** [comment]
@Grumpy-Gordon Try uninstalling WorldGuard and see if that fixes it.

**Comment by gnubufferoverflows** [comment]
Have you tried GriefPrevention 16.9? I realize it's not meant for production servers, but it looks like you're using 1.13 WorldGuard + 1.12.2 GriefPrevention on a 1.13 server.

**Comment by Grumpy-Gordon** [comment]
Thanks, I didn't realise there was a newer release. It has certainly resolved this issue.
