### ISSUE TITLE
NPE when repairing nextClaimID

### ISSUE THREAD

**Issue by Borbarad13** [GriefPrevention/GriefPrevention#377]
### What happened:
During startup the following exception occurs: "[GriefPrevention] Unable to initialize the file system data store."

### What you expected:
Normal startup without exception

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
I am trying to upgrade from Spigot v12.2 with  GriefPrevention  v16.7.1 (start up without errors)
to
Spigot v13.1 with GriefPrevention v16.10 (where I receive a null pointer exception)

### Stack trace/error or server log

```
[20:16:48 INFO]: Starting minecraft server version 1.13.1
[20:16:48 INFO]: Loading properties
[20:16:48 INFO]: Default game type: SURVIVAL
[20:16:48 INFO]: This server is running CraftBukkit version git-Spigot-68acb93-7d506c6 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
(.........)
[20:16:59 INFO]: [GriefPrevention] Enabling GriefPrevention v16.10
[20:16:59 INFO]: [GriefPrevention] Siege Configuration: Material not found: LONG_GRASS.
[20:16:59 INFO]: [GriefPrevention] Siege Configuration: Material not found: THIN_GLASS.
[20:16:59 INFO]: [GriefPrevention] Siege Configuration: Material not found: WOOD.
[20:16:59 INFO]: [GriefPrevention] Siege Configuration: Material not found: WOOL.
[20:16:59 INFO]: [GriefPrevention] Finished loading configuration.
[20:17:00 INFO]: [GriefPrevention] 52 total claims loaded.
[20:17:00 INFO]: [GriefPrevention] Unable to initialize the file system data store.  Details:
[20:17:00 INFO]: [GriefPrevention] null
[20:17:00 WARN]: java.lang.NullPointerException
[20:17:00 WARN]:        at me.ryanhamshire.GriefPrevention.DataStore.initialize(DataStore.java:144)
[20:17:00 WARN]:        at me.ryanhamshire.GriefPrevention.FlatFileDataStore.initialize(FlatFileDataStore.java:215)
[20:17:00 WARN]:        at me.ryanhamshire.GriefPrevention.FlatFileDataStore.<init>(FlatFileDataStore.java:63)
[20:17:00 WARN]:        at me.ryanhamshire.GriefPrevention.GriefPrevention.onEnable(GriefPrevention.java:303)
[20:17:00 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[20:17:00 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[20:17:00 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[20:17:00 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:428)
[20:17:00 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:342)
[20:17:00 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584)
[20:17:00 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546)
[20:17:00 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424)
[20:17:00 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[20:17:00 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
[20:17:00 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:17:00 INFO]: [GriefPrevention] Finished loading data (Database Mode).
[20:17:00 ERROR]: Error occurred while enabling GriefPrevention v16.10 (Is it up to date?)
java.lang.NullPointerException: null
        at me.ryanhamshire.GriefPrevention.FindUnusedClaimsTask.<init>(FindUnusedClaimsTask.java:38) ~[?:?]
        at me.ryanhamshire.GriefPrevention.GriefPrevention.onEnable(GriefPrevention.java:329) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-68acb93-7d506c6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-68acb93-7d506c6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-68acb93-7d506c6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:428) [spigot.jar:git-Spigot-68acb93-7d506c6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:342) [spigot.jar:git-Spigot-68acb93-7d506c6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot.jar:git-Spigot-68acb93-7d506c6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot.jar:git-Spigot-68acb93-7d506c6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot.jar:git-Spigot-68acb93-7d506c6]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot.jar:git-Spigot-68acb93-7d506c6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot.jar:git-Spigot-68acb93-7d506c6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

### GriefPrevention config.yml

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    Darkness_7: -1
    Darkness_7_nether: -1
    Darkness_7_the_end: -1
    Adventures: -1
    Creative: -1
    Farmworld_1: -1
    Farmworld_1_nether: -1
    Farmworld_1_the_end: -1
  Claims:
    Mode:
      Darkness_7: Survival
      Farmworld_1_nether: Disabled
      Darkness_7_the_end: Disabled
      Farmworld_1: Survival
      Creative: SurvivalRequiringClaims
      Darkness_7_nether: Survival
      Adventures: Survival
      Farmworld_1_the_end: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 0
    Claim Blocks Accrued Per Hour:
      Default: 30
    Max Accrued Claim Blocks:
      Default: 10000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 255
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 33
        ExceptWhenOwnerHasTotalClaimBlocks: 99999
        ExceptWhenOwnerHasBonusClaimBlocks: 99999
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 10
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome;/commandblock
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 600
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/tell;;/w;/msg;/r;/t;/mail;/feedback
    WhisperSlashCommands: /tell;/pm;/r;/w;/whisper;/t;/msg;/feedback
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 60
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      Darkness_7: true
      Darkness_7_nether: true
      Darkness_7_the_end: true
      Adventures: true
      Creative: true
      Farmworld_1: true
      Farmworld_1_nether: true
      Farmworld_1_the_end: true
    ProtectFreshSpawns: false
    PunishLogout: false
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: false
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: false
  FireSpreads: false
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds:
    - Darkness_7
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
  EndermenMoveBlocks: true
  SilverfishBreakBlocks: true
  CreaturesTrampleCrops: true
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
  Abridged Logs:
    Days To Keep: 14
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: true
      Debug: false
      Muted Chat Messages: false
```

### Plugin list (if applicable):
Shopkeepers, xInventories, MultiWorld, VoteRoulette, Some self build ones.

**Comment by RoboMWM** [comment]
While this is a bug (I guess I was trying to start refactoring this class but then realized I can't do much about abstract classes that implement a lot of stuff, but I forgot to revert changes), your nextClaimID file is corrupted and you are overwriting claims. Please fix the nextClaimID file to be a number greater than your largest-numbered claim.
