### ISSUE TITLE
Plugin Enable Error

### ISSUE THREAD

**Issue by EngineersBox** [GriefPrevention/GriefPrevention#382]
### What happened:
Produced an error pertaining to the 'golden_shovel' item, did not load the plugin beyond this point. Not GriefPrevention folder was generated and nor was the respective config files.

### What you expected:
 Expected a clean first time generation of config files and init of plugin

### Steps to reproduce:
Just starting the server produced the error

### Server and GriefPrevention version:
Server: CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
GriefPrevention: 16.11.4

### Stack trace/error or server log

```
Error occurred while enabling GriefPrevention v16.11.4 (Is it up to date?)
java.lang.NoSuchFieldError: GOLDEN_SHOVEL
	at me.ryanhamshire.GriefPrevention.GriefPrevention.loadConfig(GriefPrevention.java:648) ~[?:?]
	at me.ryanhamshire.GriefPrevention.GriefPrevention.onEnable(GriefPrevention.java:256) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

### GriefPrevention config.yml

```
There is no config, has not generated
```

**Comment by RoboMWM** [comment]
Use GP 16.8 for minecraft 1.12.2.
