### ISSUE TITLE
Could not pass event PlayerInteractEvent to GriefPrevention v16.11.5 org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by x1p** [GriefPrevention/GriefPrevention#491]
### What happened:
```
[19:32:12 ERROR]: Could not pass event PlayerInteractEvent to GriefPrevention v16.11.5
org.bukkit.event.EventException: null
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.13.2.jar:git-Paper-558]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-558]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-558]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[patched_1.13.2.jar:git-Paper-558]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:320) ~[patched_1.13.2.jar:git-Paper-558]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:287) ~[patched_1.13.2.jar:git-Paper-558]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:283) ~[patched_1.13.2.jar:git-Paper-558]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1401) ~[patched_1.13.2.jar:git-Paper-558]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[patched_1.13.2.jar:git-Paper-558]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.13.2.jar:git-Paper-558]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-558]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-558]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-558]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-558]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-558]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-558]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalStateException: Start block missed in BlockIterator
at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:172) ~[patched_1.13.2.jar:git-Paper-558]
at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:237) ~[patched_1.13.2.jar:git-Paper-558]
at me.ryanhamshire.GriefPrevention.PlayerEventHandler.getTargetBlock(PlayerEventHandler.java:2685) ~[?:?]
at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerInteract(PlayerEventHandler.java:2026) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.13.2.jar:git-Paper-558]
... 18 more
```

### What you expected:
no error

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Flying above a claim (about 30 blocks high)
2. Click right with stick
3. error
4. Profit!
Can't reproduce. So it's probably something rare. But nevertheless wanted to let it know.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: Paper version git-Paper-558
Paste of `/version GriefPrevention`: GriefPrevention version 16.11.5
WE 7 beta 5
WG 7 beta 3

### Stack trace/error or server log

```
see above

```

### GriefPrevention config.yml

```yml

on demand

```

**Comment by RoboMWM** [comment]
https://bukkit.org/threads/getlineofsight-start-block-missed-in-blockiterator.44528/#post-791569

> I've seen player.getTargetBlock() throw this on several occasions. The situation @ nisovin described is one. You can also trigger it by standing at the highest possible point in a world (y = 127) and looking up.
> As far as I can tell, the exception is harmless and can be safely caught. Just treat it as if the player has nothing useful targeted.


Apparently a long-unsolved CB bug. You could consider reporting to CB if it hasn't already been reported.
