### ISSUE TITLE
worldguard beta3 for 1.13 and fawe 1.13+ breaking version + gprevention

### ISSUE THREAD

**Issue by cicatrice74** [GriefPrevention/GriefPrevention#512]
### What happened:
I would like to use fast async worldedit for 1.13.2 spigot and to do so i need the worldguard beta3 for 1.13+ servers + fawe 1.13+ breaking version.. if i also use gpreventions the worldguard send me errors in the console

[12:47:03] [Server thread/ERROR]: Could not load 'plugins\worldguard-legacy-7.0.0-beta-03.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/CommandsManager
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot.jar:git-Spigot-f09662d-0e1cea5]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:332) ~[spigot.jar:git-Spigot-f09662d-0e1cea5]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:277) [spigot.jar:git-Spigot-f09662d-0e1cea5]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:325) [spigot.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot.jar:git-Spigot-f09662d-0e1cea5]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/CommandsManager
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:60) ~[spigot.jar:git-Spigot-f09662d-0e1cea5]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-f09662d-0e1cea5]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.minecraft.util.commands.CommandsManager
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:136) ~[spigot.jar:git-Spigot-f09662d-0e1cea5]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[spigot.jar:git-Spigot-f09662d-0e1cea5]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:60) ~[spigot.jar:git-Spigot-f09662d-0e1cea5]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-f09662d-0e1cea5]
	... 6 more

**Comment by RoboMWM** [comment]
Disable WorldGuard integration in config.

**Comment by 112RG** [comment]
It looks like WG is the problem not GP. Are you using the latest FAWE 1.13 build from there CI ?

When I load the latest FAWE GP and WG builds it loads fine

**Comment by Jikoo** [comment]
Closing in favor of #1140 - WG appears to be working fine, but ideally compatibility will be handled by an addon in the future.
