### ISSUE TITLE
1.14.2 console complaining on portal use.

### ISSUE THREAD

**Issue by NullCase** [GriefPrevention/GriefPrevention#534]
### What happened:
console complaining on portal use.

### What you expected:
nothing.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. 1.14.2
2. GP 
3. use portal
4. check console.

### Server and GriefPrevention version:
Paper version git-Paper-55 (MC: 1.14.2)
Griefprevention version 16.11.6

### Stack trace/error or server log

```

[11:02:32] [Server thread/ERROR]: Could not pass event PlayerPortalEvent to GriefPrevention v16.11.6
--
java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerPortalEvent.useTravelAgent()Z
at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerPortal(PlayerEventHandler.java:1067) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.2.jar:git-Paper-55]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-55]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-55]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.EntityPlayer.a(EntityPlayer.java:843) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.Entity.doPortalTick(Entity.java:2165) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.Entity.entityBaseTick(Entity.java:397) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:240) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:369) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2279) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:150) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:418) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:146) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:259) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1201) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-55]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-55]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]



```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

**Comment by RoboMWM** [comment]
After a couple weeks of sitting in a spigot thread this finally made its way here. Thank you.

Spigot removed the travel agent, which is used in a default off feature in GriefPrevention. I wish it wasn't completely stripped out (from what I heard the "unsustainable change" was only a modification to end portals), but oh well.

**Comment by NullCase** [comment]
will be testing 1.14.2 as plugins are updated.

i don't know what's next for GP but in case you have dev builds to test, you're more than welcome to drop a link as builds come out.

**Comment by NullCase** [comment]
yeah it's good now.

Also, portal lag which was previously a thing for GP is completely gone. This is rly quite nice.

What does this mean if someone tries to generate a new portal on claimed land?

**Comment by RoboMWM** [comment]
Portal lag was never a thing unless that default off config was enabled

**Comment by RoboMWM** [comment]
I've been hearing about a TravelAgent PR in spigot for 1.14, so this feature may come back.
