### ISSUE TITLE
Sieges cause crash on teleport into siege

### ISSUE THREAD

**Issue by CadellVDH** [GriefPrevention/GriefPrevention#564]
### What happened:
Server crashed during a siege where a player attempted to tp into a claim during an active siege.

### What you expected:
Not a crash....

### Steps to reproduce:
Player's initiated a siege, then teleported into the siege area (presumably using /tp) 
Edit: Crash was caused by a player using /home into the claim
Log leading up to error: `[21:31:07] [Server thread/INFO]: AsForce1 issued server command: /tpaccept
[21:31:11] [Async Chat Thread - #75/INFO]: ^[[m ^[[0;31;1m^[[0;35;22m[Mod]^[[0;33;22mAsForce1^[[m:^[[m alright^[[m
[21:31:14] [Async Chat Thread - #75/INFO]: ^[[m ^[[0;31;1m^[[0;35;22m[Mod]^[[0;33;22mAsForce1^[[m:^[[m tannu^[[m
[21:31:16] [Async Chat Thread - #75/INFO]: ^[[m ^[[0;31;1m^[[0;35;22m[Mod]^[[0;33;22mAsForce1^[[m:^[[m siege me^[[m
[21:31:23] [Async Chat Thread - #75/INFO]: ^[[m ^[[0;31;1m^[[0;33;1m[Member]^[[0;37;1m_Tannu_Tuva_^[[m:^[[m what that mean^[[m
[21:31:29] [Async Chat Thread - #75/INFO]: ^[[m ^[[0;31;1m^[[0;35;22m[Mod]^[[0;33;22mAsForce1^[[m:^[[m alright^[[m
[21:31:37] [Server thread/INFO]: AsForce1 issued server command: /msg jo do /siege AsForce1
[21:31:40] [Server thread/INFO]: Jorge_The_Great issued server command: /siege AsForce1
[21:31:51] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5798ms or 115 ticks behind
[21:31:56] [Server thread/INFO]: Skywalker7988 issued server command: /home
[21:32:01] [Server thread/INFO]: Skywalker7988 issued server command: /home home
[21:32:11] [Async Chat Thread - #75/INFO]: ^[[m ^[[0;31;1m^[[0;35;22m[Mod]^[[0;33;22mAsForce1^[[m:^[[m alright^[[m
[21:32:11] [Server thread/INFO]: Skywalker7988 issued server command: /back
[21:32:12] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_14_R1.ReportedException: Exception ticking world`

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: CraftBukkit version git-Spigot-4d2f30f-f1f3355 (MC: 1.14.3)
Paste of `/version GriefPrevention`: GriefPrevention version 16.11.6

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

``        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
        at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
        at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1045)
        at net.minecraft.server.v1_14_R1.Raid.y(SourceFile:259)
        at net.minecraft.server.v1_14_R1.Raid.o(SourceFile:389)
        at net.minecraft.server.v1_14_R1.PersistentRaid.a(SourceFile:72)
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:275)
`
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

``      # Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_the_end: Survival
      world: Survival
      world_nether: Survival
    PreventGlobalMonsterEggs: false
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: false
LockWoodenDoors: false
    LockTrapDoors: true
    LockFenceGates: false
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 1000
    Claim Blocks Accrued Per Hour:
      Default: 0
    Max Accrued Claim Blocks:
      Default: 0
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5000
    MinimumWidth: 5
    MinimumArea: 25
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 100
      UnusedClaimDays: 100
      AllClaims:
        DaysInactive: 100
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    FireSpreadsInClaims: false
    FireDamagesInClaims: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 0
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please don't spam
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 15
  AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: false
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: true
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: true
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksPurchaseCost: 0.04
    ClaimBlocksSellValue: 0.04
  ProtectItemsDroppedOnDeath:
    PvPWorlds: true
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: false
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds:
    - world
    BreakableBlocks:
    - AIR
    DoorsOpenDelayInSeconds: 30
    CooldownEndInMinutes: 10
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: true
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
                                         `

### Plugin list (if applicable):
Running EssentialsX for teleport commands

**Comment by CadellFastro35** [comment]
can't get the backtick formatting right, sorry I'm dumb

**Comment by CadellVDH** [comment]
Just did further testing to attempt to reproduce the issue, and it seemed to properly prevent players from teleporting into sieged areas using /home. However, there was an active Raid at the time, which was apparently the same active raid for the previous crash. The server crashed about a minute later despite no player teleporting into the claim, and the siege being over. No longer sure if sieges are the issue.

**Comment by RoboMWM** [comment]
Yea, nothing indicates GP at fault here, at least from what I can see in the messed up formatting.

**Comment by RoboMWM** [comment]
Gonna need a proper error log to investigate further.
