### ISSUE TITLE
possibility of destroying vegetables on the field by people without "/ trust"

### ISSUE THREAD

**Issue by minecraft7net** [GriefPrevention/GriefPrevention#634]
in the latest version, players have reported on survival servers the possibility of destroying vegetables on the field by people without "/ trust"

[19:47:53] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-94af569-a3fdef8 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

[19:47:57] [Server thread/INFO]: [GriefPrevention] Loading GriefPrevention v16.12.0-d4d7ac4
[19:48:05] [Server thread/INFO]: [GriefPrevention] Enabling GriefPrevention v16.12.0-d4d7ac4
[19:48:05] [Server thread/INFO]: [GriefPrevention] Siege Configuration: Material not found: LONG_GRASS.
[19:48:05] [Server thread/INFO]: [GriefPrevention] Siege Configuration: Material not found: THIN_GLASS.
[19:48:05] [Server thread/INFO]: [GriefPrevention] Siege Configuration: Material not found: WOOD.
[19:48:05] [Server thread/INFO]: [GriefPrevention] Siege Configuration: Material not found: WOOL.
[19:48:05] [Server thread/INFO]: [GriefPrevention] Finished loading configuration.
[19:48:05] [Server thread/INFO]: [GriefPrevention] 1678 total claims loaded.
[19:48:05] [Server thread/INFO]: [GriefPrevention] Customizable messages loaded.
[19:48:05] [Server thread/INFO]: [GriefPrevention] Successfully hooked into WorldGuard.
[19:48:05] [Server thread/INFO]: [GriefPrevention] Finished loading data (File Mode).
[19:48:05] [Server thread/INFO]: [GriefPrevention] GriefPrevention requires Vault for economy integration.
[19:48:05] [Server thread/INFO]: [GriefPrevention] Attempting to load Vault...
[19:48:05] [Server thread/INFO]: [GriefPrevention] Vault loaded successfully!
[19:48:05] [Server thread/INFO]: [GriefPrevention] Looking for a Vault-compatible economy plugin...
[19:48:05] [Server thread/INFO]: [GriefPrevention] Hooked into economy: CMIEconomy.
[19:48:05] [Server thread/INFO]: [GriefPrevention] Ready to buy/sell claim blocks!
[19:48:05] [Server thread/INFO]: [GriefPrevention] Boot finished.
[19:48:12] [Server thread/INFO]: [TradeMe] GriefPrevention plugin was found!

**Comment by RoboMWM** [comment]
Need all details in issue template.

**Comment by minecraft7net** [comment]
### What happened:
_What you saw_

possibility of destroying vegetables on the field by people without "/ trust"
players on survival server reports that they claim terrain and "other" "untrusted" people/players can enter claim and "destroy they vegetables on protected claim"

### What you expected:
_What you expected to see_

vegetables are protected - players report it works before latest update.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. player protect area
2. player build a vegetables farm
3. other player enter and destroy vegetables

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
Paste of `/version GriefPrevention`:

[09:52:51] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-94af569-a3fdef8 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

[09:53:10] [Server thread/INFO]: GriefPrevention version 16.12.0-d4d7ac4


### Stack trace/error or server log

no errors in log

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_nether: Disabled
      world: Survival
      world_the_end: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 1000
    Claim Blocks Accrued Per Hour:
      Default: 500
    Max Accrued Claim Blocks:
      Default: 120000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: -1
      UnusedClaimDays: -1
      AllClaims:
        DaysInactive: -1
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 3
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/tell;/global;/local;/w;/msg;/r;/t
    WhisperSlashCommands: /tell;/pm;/r;/w;/whisper;/t;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be punted.
    BanOffenders: false
    BanMessage: Punted for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 60
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 10
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 100.0
    ClaimBlocksSellValue: 10.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: false
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 0
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false


### Plugin list (if applicable):

**Comment by RoboMWM** [comment]
What are the vegetable items in question? How are they destroyed? (trampling? Or breaking with hand?)

**Comment by minecraft7net** [comment]
destruction by scanning / hopping over / on these vegetables / crops. veggies are probably all. wheat, watermelons, but not blocks only what grows from seeds.

**Comment by minecraft7net** [comment]
destruction by jumping over crops / all vegetables such as: potatoes, carrots, wheat, beetroot, pumpkin and watermelon stalks

**Comment by RoboMWM** [comment]
Watermelons are fruits.
So you mean farm blocks/plants grown on farmland.

Idk what scanning is. So I'm assuming it's trampling.

Have you tested 16.11.6 on server 1.14.4? Because I don't recall any changes to the event handler that listens to that.

**Comment by niqofdez** [comment]
My players reported the same problem. Any player (without trust) can jump over the crops and destroy them.

**Comment by RoboMWM** [comment]
Please see my last comment, that information would be helpful

**Comment by ShaneBeee** [comment]
I just tested on a previous version:
`GriefPrevention version 16.12.0-6f35aab`
as well as the latest:
`GriefPrevention version 16.12.0-d4d7ac4`

Went into another player's claim, jumped around on a crop, didn't break. 
Tried to hit it, didn't break.
No matter what I try, I can't break the crop.
I can not replicate this issue.

**Comment by ShaneBeee** [comment]
Update:
I copied your config, (I dont have vault nor an economy system on my server because its a test server) and I got this error:
```
[00:08:45 ERROR]: Error occurred while enabling GriefPrevention v16.12.0-d4d7ac4 (Is it up to date?)
java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
	at me.ryanhamshire.GriefPrevention.GriefPrevention.onEnable(GriefPrevention.java:362) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-209]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-209]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-209]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-209]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-209]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.reload(CraftServer.java:859) ~[patched_1.14.4.jar:git-Paper-209]
	at org.bukkit.Bukkit.reload(Bukkit.java:610) ~[patched_1.14.4.jar:git-Paper-209]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.14.4.jar:git-Paper-209]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-209]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-209]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:456) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-209]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.economy.Economy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.4.jar:git-Paper-209]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-209]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
	... 17 more
[00:18:10 INFO]: [GriefPrevention] Disabling GriefPrevention v16.12.0-d4d7ac4
[00:18:10 INFO]: [GriefPrevention] GriefPrevention disabled.
```
With this error, Im able to break crops, obviously because:
```
[00:18:10 INFO]: [GriefPrevention] Disabling GriefPrevention v16.12.0-d4d7ac4
[00:18:10 INFO]: [GriefPrevention] GriefPrevention disabled.
```

I changed your config options from this:
```yaml
  Economy:
    ClaimBlocksPurchaseCost: 100.0
    ClaimBlocksSellValue: 10.0
```
to 
```yaml
  Economy:
    ClaimBlocksPurchaseCost: 0
    ClaimBlocksSellValue: 0
```
I reloaded the server, Im now no longer able to break crops!

**NEXT**
I stopped my server, downloaded EssentialsX and Vault. I changed the config options back to your config, exactly the same.
I can not break crops. 

Do you have any errors when the plugin loads?

**Comment by minecraft7net** [comment]
./20190616.off/GriefPrevention-v16.11.6.jar <-- it may work here (agree) it was compiled from github repo
./20190824.off/GriefPrevention-16.12alpha2.jar <-- it may work here (agree) it was compiled from github repo
./plugins/GriefPrevention-16.12.0.jar <---current loaded

**Comment by niqofdez** [comment]
@minecraft7net Did you find the solution to this?

**Comment by niqoar** [comment]
Hey @RoboMWM, I've discovered that this happens with NoCheatPlus with the "dealdamage" option in true within the nofall options.

**Comment by niqofdez** [comment]
Hey @RoboMWM, I've discovered that this happens with NoCheatPlus with the "dealdamage" option in true

https://github.com/NoCheatPlus/Docs/wiki/%5BMoving%5D-Nofall

**Comment by RoboMWM** [comment]
that should deal damage to the player who attempts to cheat fall damage detection. No idea why it would also cause crops to be damaged. How did you determine this?

**Comment by niqofdez** [comment]
I simply installed all the plugins of my server on localhost and I assumed that it could be that and I tried. I uploaded a small demostrative video: https://youtu.be/PtLMPFPMjOs

**Comment by RoboMWM** [comment]
So it happens when only NCP and GP are installed?

**Comment by niqofdez** [comment]
Yes, I tested only with GriefPrevention, NoCheatPlus, ProtocolLib and Vault installed
 
*Paper version git-Paper-86 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
*GriefPrevention v16.12.0-d4d7ac4
*NoCheatPlus v3.17-SNAPSHOT-b5.5.1 (Fork of MarkElf)
*Vault v1.7.2-b107
*ProtocolLib v4.5.0

**Comment by RoboMWM** [comment]
Ok, and you can't reproduce without NCP, correct? If so, then you'll need to report this issue to MarkElf.

**Comment by niqofdez** [comment]
Correct, without NCP I can't break protected crops. I will send a message to MarkElf!

**Comment by RoboMWM** [comment]
@minecraft7net Please also try to reproduce with above info.

**Comment by MrPowerGamerBR** [comment]
Can confirm that disabling `dealdamage`  in NoCheatPlus' configuration fixes the issue.

**Comment by RoboMWM** [comment]
I know this was reported to the NCP fork's issue tracker but I can't seem to find it. It was resolved there though by them also firing the appropriate event for this. (Which I believe was EntityChangeBlockEvent, I think.) 

The issue originated from them as they were trying to mimic the effects of fall damage when it determines a player was attempting to avoid fall damage. He added effects that this would cause in the world, and initially only checked for PlayerInteractEvent. BigScary doesn't use this event because that event is used for a lot of things, and doing a block material check each time is a bit costly compared to the less-often-called EntityChangeBlockEvent.
