### ISSUE TITLE
SQL Error, Players claim blocks being reset

### ISSUE THREAD

**Issue by Hman1250** [GriefPrevention/GriefPrevention#666]
I've had a few complaints regarding players having their claim blocks reset upon joining the server. Upon going through the server logs, I've encountered this upon player entry.
```
[02:11:52] [Craft Scheduler Thread - 69/INFO]: [GriefPrevention] 2543a270-a4b8-48ee-9cf7-aa9b653c92a6 com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 59,975 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3462)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3905)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2011)
	at me.ryanhamshire.GriefPrevention.DatabaseDataStore.getPlayerDataFromStorage(DatabaseDataStore.java:491)
	at me.ryanhamshire.GriefPrevention.CleanupUnusedClaimPreTask.run(CleanupUnusedClaimPreTask.java:42)
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3014)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3472)
	... 15 more
```
This occurred 10 minutes after my server restarted, however some players have reported their issues at different times. Any particular reason why this is happening?

**Comment by RoboMWM** [comment]
Sounds like your MySQL database server or the connection to it is struggling.

**Comment by TomLewis** [comment]
Check your disk hasn't run out of space

**Comment by nouish** [comment]
### Reproducing this problem

Default MySQL [`wait_timeout`](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout) is 28800 seconds (8 hours). After sitting idle for this long, MySQL will close the connection, throwing the exception in OP when GP next tries to use this connection.

To save on time, to reproduce this locally within a minute, set `wait_timeout` to something lower (for example 30 seconds) on the SESSION (`SET SESSION wait_timeout = 30`). Now join your local server, and idle 30 seconds, then create/resize a claim. You should see the same exception as reported here.

You can test by adding the following SQL command [here](https://github.com/TechFortress/GriefPrevention/blob/1edd0a921e1a5b6ae4db16b38c79c8f77d428c4f/src/main/java/me/ryanhamshire/GriefPrevention/DatabaseDataStore.java#L650):

```sql
try (Statement stmt = databaseConnection.createStatement()) {
    stmt.execute("SET SESSION wait_timeout = 30");
}
```

____

While this can be solved by making GP validate and reestablish connections when needing one, or pass this responsibility onto a [connection pool](https://github.com/brettwooldridge/HikariCP), this is only part of the problem.

ALL operations are perfomed in auto-commit mode, making GP prone to data loss and 'bad state' (corruption) when executing series of commands like this:

https://github.com/TechFortress/GriefPrevention/blob/1edd0a921e1a5b6ae4db16b38c79c8f77d428c4f/src/main/java/me/ryanhamshire/GriefPrevention/DatabaseDataStore.java#L424-L428

Sure, in that particular instance it seems to make an effort to validate the connection first, but what if between those calls the connection DOES timeout or there's a power outage? You've just deleted the data from disk. Same result if the disk is full and the second (write) operation fails. It would be better to rollback and hold onto the data as is, rather than to lose that too.

There are more instances of this sequence - one obvious one is the following, which could result in loss of player data:

https://github.com/TechFortress/GriefPrevention/blob/1edd0a921e1a5b6ae4db16b38c79c8f77d428c4f/src/main/java/me/ryanhamshire/GriefPrevention/DatabaseDataStore.java#L538-L539

**Comment by good3n** [comment]
Any progress on getting this fixed? This is a huge bug.

**Comment by noaskers** [comment]
Happend to me aswell since 16.18.5
