### ISSUE TITLE
crash on Glowstone

### ISSUE THREAD

**Issue by mio-19** [GriefPrevention/GriefPrevention#702]
### What happened:
crash on Glowstone

### What was expected:
_What you expected to see_

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. download Glowstone and this plugin
2. run

### Stack trace/error or server log
```
01:10:09 [SEVERE] Error occurred while enabling GriefPrevention v16.12.0-d4d7ac4 (Is it up to date?)
java.lang.NoSuchFieldError: GOLDEN_SHOVEL
	at me.ryanhamshire.GriefPrevention.GriefPrevention.loadConfig(GriefPrevention.java:661)
	at me.ryanhamshire.GriefPrevention.GriefPrevention.onEnable(GriefPrevention.java:263)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	at net.glowstone.GlowServer.enablePlugins(GlowServer.java:1346)
	at net.glowstone.GlowServer.start(GlowServer.java:819)
	at net.glowstone.GlowServer.run(GlowServer.java:625)
	at net.glowstone.GlowServer.main(GlowServer.java:489)
01:10:09 [INFO] Disabling GriefPrevention v16.12.0-d4d7ac4
01:10:09 [SEVERE] Error occurred while disabling GriefPrevention v16.12.0-d4d7ac4 (Is it up to date?)
java.lang.NullPointerException
	at me.ryanhamshire.GriefPrevention.GriefPrevention.onDisable(GriefPrevention.java:3211)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:354)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	at net.glowstone.GlowServer.enablePlugins(GlowServer.java:1346)
	at net.glowstone.GlowServer.start(GlowServer.java:819)
	at net.glowstone.GlowServer.run(GlowServer.java:625)
	at net.glowstone.GlowServer.main(GlowServer.java:489)
```
### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by bigpresh** [comment]
Hmm.  GriefPrevention is written for Bukkit/Spigot - it may well require quite a few changes to work in Glowstone, so I guess that the answer may well just be "yeah, we don't support that, sorry".

On the other hand, if any changes required are minimal and it works well otherwise, it would be nice to be able to run on it.

(For reference, this issue is talking about running under the Glowstone open-source Minecraft implementation - https://glowstone.net/ - not to do with glowstone as in the material in Minecraft.)

**Comment by Jikoo** [comment]
Please download the correct version of GP for your Minecraft version. 1.12 is not supported by modern GP due to changes in the Bukkit API.

**Comment by RoboMWM** [comment]
I believe you need to use GP 16.8 for Bukkit implementations on 1.12.2.
