### ISSUE TITLE
Error After Upgrading to 1.15.2 Server

### ISSUE THREAD

**Issue by Bludwood** [GriefPrevention/GriefPrevention#704]
Team - I recently upgraded my Spigot server from 1.15.1 to 1.15.2 by building the new server jar and replacing the 1.15.1 jar with the 1.15.2 jar. When running the server, hitting any block within my claimed with a sword (or probably anything) produces the exception below. Please advise.

[20:58:03] [Server thread/INFO]: [SpawnerSilk] Enabling SpawnerSilk v3.0
[20:58:03] [Server thread/INFO]: [GriefPrevention] Enabling GriefPrevention v16.12.0-d4d7ac4
[20:58:03] [Server thread/INFO]: [GriefPrevention] Finished loading configuration.
[20:58:03] [Server thread/INFO]: [GriefPrevention] 9 total claims loaded.
[20:58:04] [Server thread/INFO]: [GriefPrevention] Customizable messages loaded.
[20:58:04] [Server thread/INFO]: [GriefPrevention] Finished loading data (File Mode).
[20:58:04] [Server thread/INFO]: [GriefPrevention] Boot finished.
[20:58:04] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[20:58:04] [Server thread/INFO]: Done (9.110s)! For help, type "help"
[20:59:27] [User Authenticator #1/INFO]: UUID of player Bludwood is c9fc8469-471f-4a87-a851-b3ae297e8239
[20:59:27] [Server thread/INFO]: Bludwood[/35.136.120.225:50754] logged in with entity id 301 at ([world]157.24220189590156, 42.0, -306.4340393062035)
[20:59:35] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to GriefPrevention v16.12.0-d4d7ac4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:442) ~[spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:409) ~[spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:137) ~[spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1197) ~[spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoSuchMethodError: org.bukkit.craftbukkit.v1_15_R1.util.CraftLegacy.modern_values()[Lorg/bukkit/Material;
        at me.ryanhamshire.GriefPrevention.PlayerEventHandler$2.<clinit>(PlayerEventHandler.java:2671) ~[?:?]
        at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onLeftClickWatchList(PlayerEventHandler.java:2671) ~[?:?]
        at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerInteract(PlayerEventHandler.java:1621) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.2.jar:git-Spigot-800b93f-efd6cf5]
        ... 20 more

**Comment by RoboMWM** [comment]
I'm not sure how people are submitting issues without [selecting a template.](https://github.com/TechFortress/GriefPrevention/issues/new/choose)
