### ISSUE TITLE
ClassCastException when getting commands from a non-JavaPlugin plugin

### ISSUE THREAD

**Issue by ha29mya3** [GriefPrevention/GriefPrevention#707]
### What happened:
Could not pass event PlayerCommandPreprocessEvent to GriefPrevention v16.12.0-d4d7ac4

### What was expected:
nothing

### Steps to reproduce:

issue a command

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
`This server is running Paper version git-Paper-84 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Previous version: git-Paper-83 (MC: 1.15.2)
You are running the latest version
`
Paste of `/version GriefPrevention`: 
`
GriefPrevention version 16.12.0-d4d7ac4
`

### Stack trace/error or server log

```
[10:41:27 ERROR]: Could not pass event PlayerCommandPreprocessEvent to GriefPrevention v16.12.0-d4d7ac4
java.lang.ClassCastException: nz.co.jammehcow.lukkit.environment.plugin.LukkitPlugin incompatible with org.bukkit.plugin.java.JavaPlugin
	at me.ryanhamshire.GriefPrevention.PlayerEventHandler.getCommandCategory(PlayerEventHandler.java:551) ~[?:?]
	at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerCommandPreprocess(PlayerEventHandler.java:394) ~[?:?]
	at java.lang.invoke.VirtualHandle.invokeExact_thunkArchetype_V(Unknown Source) ~[?:?]
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(Unknown Source) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[papermc.jar:git-Paper-84]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[papermc.jar:git-Paper-84]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[papermc.jar:git-Paper-84]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:561) ~[papermc.jar:git-Paper-84]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1812) ~[papermc.jar:git-Paper-84]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1628) ~[papermc.jar:git-Paper-84]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[papermc.jar:git-Paper-84]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[papermc.jar:git-Paper-84]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[papermc.jar:git-Paper-84]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$3743/000000002815EF50.run(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[papermc.jar:git-Paper-84]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[papermc.jar:git-Paper-84]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[papermc.jar:git-Paper-84]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[papermc.jar:git-Paper-84]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[papermc.jar:git-Paper-84]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[papermc.jar:git-Paper-84]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[papermc.jar:git-Paper-84]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[papermc.jar:git-Paper-84]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[papermc.jar:git-Paper-84]
	at java.lang.Thread.run(Unknown Source) [?:?]

```
### GriefPrevention config.yml

default
### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment]
Missing version info.

**Comment by ha29mya3** [comment]
added

**Comment by RoboMWM** [comment]
`nz.co.jammehcow.lukkit.environment.plugin.LukkitPlugin`

What is this plugin and why has it registered something else in the PluginManager??? I'll add a check for this but very curious why it has something in here that doesn't extend `JavaPlugin`
