### ISSUE TITLE
Unknown exception while executing task 36880. GriefPrevention v16.13.0-0cf0171

### ISSUE THREAD

**Issue by NullCase** [GriefPrevention/GriefPrevention#744]
### What happened:
10.03 11:44:51 [Server] WARN [GriefPrevention] Plugin GriefPrevention v16.13.0-0cf0171 generated an exception while executing task 36880
10.03 11:44:51 [Server] INFO java.lang.NullPointerException: null

### What was expected:
Nothing.

### Steps to reproduce:
unclear. was observed in the console feed.

### Server and GriefPrevention version:
GriefPrevention version 16.13.0-0cf0171
Paper version git-Paper-129 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Stack trace/error or server log

```
10.03 11:44:51 [Server] WARN [GriefPrevention] Plugin GriefPrevention v16.13.0-0cf0171 generated an exception while executing task 36880
10.03 11:44:51 [Server] INFO java.lang.NullPointerException: null
```

### GriefPrevention config.yml

```
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world: Survival
      world_nether: Survival
      world_the_end: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 0
    Claim Blocks Accrued Per Hour:
      Default: 0
    Max Accrued Claim Blocks:
      Default: 1000000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: -1
    ExtendIntoGroundDistance: 5
    MinimumWidth: 2
    MinimumArea: 4
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_AXE
    Expiration:
      ChestClaimDays: 60
      UnusedClaimDays: 60
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 2147483647
        ExceptWhenOwnerHasBonusClaimBlocks: 2147483647
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/tell;/global;/local;/w;/msg;/r;/t
    WhisperSlashCommands: /tell;/pm;/r;/w;/t;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 60
    Logout Message Delay In Seconds: 10
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksPurchaseCost: 100.0
    ClaimBlocksSellValue: 100.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: false
  LimitTreeGrowth: false
  CheckPistonMovement: true
  LimitPistonsToLandClaims: true
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 6
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: false
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 365
  Abridged Logs:
    Days To Keep: 14
    Included Entry Types:
      Social Activity: false
      Suspicious Activity: false
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

```

### Plugin list (if applicable):

Plugins (25): Bot*, CheaperPhysicsEvent, ChestShop, ChestShopNotifier*, ClaimslistClassifier, CoreProtect, dynmap*, Dynmap-GriefPrevention*, EnjinMinecraftPlugin, Essentials, EssentialsChat, EssentialsSpawn, GPAuctions, GPRealEstate, GriefPrevention, GroupManager, InGameMotd, PlaceholderAPI, ProtocolLib, PVPToggle*, SuperTrailsPro*, Vault, WorldBorder*, WorldEdit, WorldGuard

**Comment by RoboMWM** [comment]
There should be more to this. If there is no stacktrace, this means that the error has been printed before. See if you can find the first instance of it in your server log.

**Comment by NullCase** [comment]
OK, here's the first instance.

```

[09:06:47] [Craft Scheduler Thread - 59/WARN]: [GriefPrevention] Plugin GriefPrevention v16.13.0-0cf0171 generated an exception while executing task 2344
--
java.lang.NullPointerException: null
at me.ryanhamshire.GriefPrevention.FlatFileDataStore.getPlayerDataFromStorage(FlatFileDataStore.java:610) ~[?:?]
at me.ryanhamshire.GriefPrevention.CleanupUnusedClaimPreTask.run(CleanupUnusedClaimPreTask.java:42) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-129]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-129]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-129]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]


```

**Comment by Jikoo** [comment]
Ah. This is because I am an idiot.

**Comment by NullCase** [comment]
>GriefPrevention version 16.13.0-0f82170

It looks like you fixed it in `Hoo boy` because the latest snapshot is not reporting this issue.

Seems like this can be closed, but in case it's an issue until merged you're welcome to close this when rdy.
