### ISSUE TITLE
BlockIdsRequiringContainerTrust doesn't work

### ISSUE THREAD

**Issue by Krosta8** [GriefPrevention/GriefPrevention#764]
### What happened:
[GriefPrevention] ERROR: Unable to read a material entry from the config file. Please update your config.yml.
I was trying to add material in BlockIdsRequiringContainerTrust

### What was expected:
After adding the block id - the block should require ContainerTrust.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. In config.yml set for section Mods: BlockIdsRequiringContainerTrust: [1] (doesn't matter, which block you try to add, nothing works)
2. Reload GriefPrevention
3. Error in Console.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
Mohist version 343c500 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2847)
Paste of `/version GriefPrevention`: 
GriefPrevention version 16.8

### Stack trace/error or server log
[GriefPrevention] ERROR: Unable to read a material entry from the config file. Please update your config.yml.

### Debugging steps attempted

- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment]
You cannot use IDs anymore since 1.13. Please use https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html for a list of valid materials.

**Comment by RoboMWM** [comment]
Oh I see, you're using 1.12.2. I'll doublecheck when we switched to materials...

**Comment by RoboMWM** [comment]
This check has been in here since at least GP 15. I'm not sure where to find a list of 1.12 materials though.

**Comment by Krosta8** [comment]
As far as I know, I have to use IDs, but it was not working. And when I tried to use "names" like minecraft:dirt, it said error with ":". So, I am not sure, what to do, maybe there is nothing, what I can do about it :/

**Comment by RoboMWM** [comment]
No, it has to be a bukkit material enum

**Comment by Krosta8** [comment]
Oh, ok. I tried, just now, to use "STONE" or "WOOD" (which is in the config already in "Siege"). I also look into this: https://helpch.at/docs/1.12.2/index.html?org/bukkit/Material.html 
Still the same problem in config, example: "WOOD     <-- can't understand this entry, see BukkitDev documentation"

Also I tried to use command /gpblockinfo and it just throw me An internal error occurred. 

Just to remind, I am using Mohist. The problem is with modded blocks and I wanted to add them via this option to needed container trust.
I love this plugin, so I wanted to be able to use it with mods too :/

**Comment by RoboMWM** [comment]
Oh. In that case I have no idea.

> Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2847)

Nothing in here indicates Bukkit to me, so idk how this plugin is even running there. Sorry idk. Try looking in their documentation for their implementation of Bukkit's Material enum.

**Comment by Krosta8** [comment]
I think, that that's not the problem, because Mohist is using spigot API too (somehow). To be sure, that this is not the problem, I made a fresh new server (1.12.2), just with GriefPrevention and used Spigot: **This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**
Still the same, cannot add anything in config (even already added blocks in Siege mod) and with /gpblockinfo just got error.
Also I tried to look into commits (Just try to look into something with changes to block IDs) and found this, if this can help with this problem: https://github.com/TechFortress/GriefPrevention/commit/8040a17e5d0ec44d5544aa42e4318362c7ea2405
`[12:48:34 INFO]: Krosta8 issued server command: /gpblockinfo
[12:48:34 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'gpblockinfo' in plugin GriefPrevention v16.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[TechnicPack.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[TechnicPack.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[TechnicPack.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399) [TechnicPack.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [TechnicPack.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [TechnicPack.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [TechnicPack.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [TechnicPack.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_241]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [TechnicPack.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [TechnicPack.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [TechnicPack.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [TechnicPack.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [TechnicPack.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.util.IllegalFormatConversionException: d != org.bukkit.Material
        at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source) ~[?:1.8.0_241]
        at java.util.Formatter$FormatSpecifier.printInteger(Unknown Source) ~[?:1.8.0_241]
        at java.util.Formatter$FormatSpecifier.print(Unknown Source) ~[?:1.8.0_241]
        at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_241]
        at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_241]
        at java.lang.String.format(Unknown Source) ~[?:1.8.0_241]
        at me.ryanhamshire.GriefPrevention.GriefPrevention.onCommand(GriefPrevention.java:2649) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[TechnicPack.jar:git-Spigot-dcd1643-e60fc34]
        ... 15 more`

EDIT://
I tried an older version from newest for 1.12.2 (16.8) to oldest on github releases (15.2.3), every version doesn't work even with ID or Bukkit enum. 
Command /gpblockinfo is working on all version from 15.2.3 to 16.7.1 (It says for example "STONE(1:0)". I tried to add that to the list of blocksID and it says error (tried just "STONE", "1:0", "1").

**Comment by RoboMWM** [comment]
Yes, `/gpblockinfo` was broken in 16.8.

I'm not sure how this config section worked, as even BigScary himself left that as deprecated. Eventually we cleaned it out entirely for 1.13 iirc. You can paste your config (you're probably doing it wrong in yaml, maybe, idk), but idk other than that, especially since this is totally gone in current versions.

**Comment by Krosta8** [comment]
https://pastebin.com/tsizvM91 This is fresh new config without any changes, only the section "Mods". I tried a few different variants. 
This was generated with version 16.8

The reason, why I need this, are mods. Modded blocks (such as Macerator, Electric Furnace, ...) are not protected from taking item from their inventory. 
I wanted to use this plugin also on 1.15.2 with mods :/
