### ISSUE TITLE
1.15.2 Console errors on second corner selection

### ISSUE THREAD

**Issue by StarFluxGames** [GriefPrevention/GriefPrevention#781]
### What happened:
Selecting first claim corner works fine, although selecting second claim corner does absolutely nothing.

### What was expected:
A completed claim after second selection

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Select claim corner 1
2. Select claim corner 2
3. Error

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paper-165
16.8

### Stack trace/error or server log

```
[06:37:20] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to GriefPrevention v16.8
java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/permission/RegionPermissionModel
	at me.ryanhamshire.GriefPrevention.WorldGuardWrapper.canBuild(WorldGuardWrapper.java:36) ~[?:?]
	at me.ryanhamshire.GriefPrevention.DataStore.createClaim(DataStore.java:863) ~[?:?]
	at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerInteract(PlayerEventHandler.java:2440) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-165]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-165]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-165]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-165]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-165]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[patched_1.15.2.jar:git-Paper-165]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1378) ~[patched_1.15.2.jar:git-Paper-165]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-165]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-165]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-165]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-165]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-165]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-165]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-165]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1053) ~[patched_1.15.2.jar:git-Paper-165]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1046) ~[patched_1.15.2.jar:git-Paper-165]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-165]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1016) ~[patched_1.15.2.jar:git-Paper-165]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:939) ~[patched_1.15.2.jar:git-Paper-165]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment]
Have you tried... updating GP?

**Comment by StarFluxGames** [comment]
I feel absolutely stupid. I downloaded the updated version but never put it in...
Apologies.

**Comment by RoboMWM** [comment]
No problem, thanks for the update!
