### ISSUE TITLE
Plugin Not Loading (already initialized)

### ISSUE THREAD

**Issue by zlarr** [GriefPrevention/GriefPrevention#829]
### What happened:
The plugin was working when I first downloaded it, but then it stopped showing/loading when I start my server. Now I get this error
![pluginerror](https://user-images.githubusercontent.com/65933500/82855327-deac5700-9ebf-11ea-941a-f426952226aa.PNG)

### What was expected:
_What you expected to see_

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
No idea.
### Server and GriefPrevention version:
Latest
### Stack trace/error or server log

[19:35:59 ERROR]: Could not load 'plugins\GriefPrevention (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:140) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:359) ~[patched_1.15.2.jar:git-Paper-256]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-256]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) ~[patched_1.15.2.jar:git-Paper-256]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:203) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52) ~[patched_1.15.2.jar:git-Paper-256]
        at me.ryanhamshire.GriefPrevention.GriefPrevention.<init>(GriefPrevention.java:71) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:136) ~[patched_1.15.2.jar:git-Paper-256]
        ... 6 more
Caused by: java.lang.IllegalStateException: Initial initialization
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:206) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52) ~[patched_1.15.2.jar:git-Paper-256]
        at com.github.hornta.wild.WildPlugin.<init>(WildPlugin.java:29) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:136) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-256]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:336) ~[patched_1.15.2.jar:git-Paper-256]
        ... 4 more
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.
Doesnt exist

### Plugin list (if applicable):
AdvancedEnchantments*, AreaShop, ArmorStandTools, BeastWithdraw, DisablePlayerHunger, EnjinMinecraftPlugin, Essentials, EssentialsSpawn, ExtraContexts*, Factions, HolographicDisplays, HolographicExtension, Jobs, LuckPerms, mcMMO, MultiChat*, Multiverse-Core*, MythicMobs, OldCombatMechanics, PL-Hide, PlaceholderAPI, ProtocolLib, ServerNPC, ShopGUIPlus, SilkSpawners, SimpleBackup*, TAB, UltimateKits, UltimateStacker, UltraCustomizer, UltraCustomizerPlus, Vault, ViaVersion*, Votifier, Wild, WorldEdit, WorldGuard
### Debugging steps attempted
<!--These will be checkboxes you can click after creating the issue)-->
- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment]
I think you have two of the same jar, or rather, you did a plugman load. Don't do that and start the server normally.

Also, `latest` is not a version.

**Comment by RoboMWM** [comment]
If you still believe this is an issue, and you've double checked to make sure that you don't have any stray jars lying around, and are using an updated server version, then please open a new issue filling out the template properly.
