### ISSUE TITLE
GP dev v20 testing - on startup, NoClass DefFoundError, NoSuchFieldError 

### ISSUE THREAD

**Issue by NullCase** [GriefPrevention/GriefPrevention#831]
Hi @RoboMWM this is my first time testing GP 20. It looks like I'll be able to test this sometimes. I don't know how useful this is, but here's what happened on startup.

### What happened:
Plugins that depend on GriefPrevention failed to load (GPR, GPAuctions, ClaimClassifier).

### What was expected:
Plugins load with GP.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Update to [GP 20.0.0-alpha-d93730ff](https://ci.appveyor.com/project/RoboMWM39862/griefprevention/build/artifacts)
2. Use one of the above named plugins, or perhaps anything which hooks into GP.
3. Start the server.
4. Observe console/log files for errors.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: git-Paper-318
Paste of `/version GriefPrevention`: 20.0.0-alpha-d93730ff

### Stack trace/error or server log

```
[00:43:06] [Server thread/ERROR]: Error occurred while enabling GPRealEstate v1.6.0 (Is it up to date?)
java.lang.NoClassDefFoundError: me/ryanhamshire/GriefPrevention/Claim
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_251]
	at java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:1.8.0_251]
	at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:695) ~[patched_1.15.2.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:640) ~[patched_1.15.2.jar:git-Paper-318]
	at me.SuperPyroManiac.GPR.feature.MailSellerOnSale.<init>(MailSellerOnSale.java:22) ~[?:?]
	at me.SuperPyroManiac.GPR.GPRealEstate.onEnable(GPRealEstate.java:68) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-318]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-318]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-318]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-318]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-318]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.ClassNotFoundException: me.ryanhamshire.GriefPrevention.Claim
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-318]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-318]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	... 16 more
[00:43:06] [Server thread/INFO]: [GPRealEstate] Disabling GPRealEstate v1.6.0
[00:43:06] [Server thread/INFO]: [GPAuctions] Enabling GPAuctions v1.2.3 commit 45c5ed5
[00:43:06] [Server thread/ERROR]: Error occurred while enabling GPAuctions v1.2.3 commit 45c5ed5 (Is it up to date?)
java.lang.NoSuchFieldError: dataStore
	at com.robomwm.gpauctions.GPAuctions.onEnable(GPAuctions.java:32) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-318]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-318]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-318]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-318]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-318]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[00:43:06] [Server thread/INFO]: [GPAuctions] Disabling GPAuctions v1.2.3 commit 45c5ed5
[00:43:06] [Server thread/INFO]: [ClaimslistClassifier] Enabling ClaimslistClassifier v1.5
[00:43:06] [Server thread/ERROR]: Error occurred while enabling ClaimslistClassifier v1.5 (Is it up to date?)
java.lang.NoSuchFieldError: dataStore
	at com.robomwm.claimslistclassifier.ClaimslistClassifier.onEnable(ClaimslistClassifier.java:38) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-318]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-318]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-318]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-318]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-318]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[00:43:06] [Server thread/INFO]: [ClaimslistClassifier] Disabling ClaimslistClassifier v1.5
[00:43:06] [Server thread/ERROR]: [ClaimslistClassifier] Claim names could not be saved! Any newly-named claims will not persist a server restart.
[00:43:06] [Server thread/WARN]: java.lang.NullPointerException
[00:43:06] [Server thread/WARN]: 	at com.robomwm.claimslistclassifier.ClaimslistClassifier.saveClaimNames(ClaimslistClassifier.java:131)
[00:43:06] [Server thread/WARN]: 	at com.robomwm.claimslistclassifier.ClaimslistClassifier.onDisable(ClaimslistClassifier.java:123)
[00:43:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[00:43:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415)
[00:43:06] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516)
[00:43:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384)
[00:43:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[00:43:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
[00:43:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
[00:43:07] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
[00:43:07] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[00:43:07] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900)
[00:43:07] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[00:43:07] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Plugin list (if applicable):
GPR
GPAuctions
ClaimClassifier

**Comment by RoboMWM** [comment]
Yea, all addons are expected to break with the state of dev/v20. It's effectively a rebuild. As per the recent comments #63 no more work will be done on the dev/v20 branch, and will instead be used as a reference/blueprint for further development of the current version (master branch).

Thank you for testing though, very much appreciated and will be moreso desired as we start changing stuff around/refactoring v16 (which will be soon).
