### ISSUE TITLE
ERROR Could not pass event PlayerTeleportEvent to GriefPrevention v16.13.0

### ISSUE THREAD

**Issue by superzyr** [GriefPrevention/GriefPrevention#855]
### What happened:
_What you saw_

### What was expected:
_What you expected to see_

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Step 1.
2. Step 2.
3. ???
4. Profit!

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
Paste of `/version GriefPrevention`: 

### Stack trace/error or server log

```
23.06 12:14:34 [Server] ERROR Could not pass event PlayerTeleportEvent to GriefPrevention v16.13.0
23.06 12:14:34 [Server] INFO java.lang.NullPointerException: null
23.06 12:14:34 [Server] INFO at java.lang.String.replace(String.java:2143) ~[?:?]
23.06 12:14:34 [Server] INFO at me.ryanhamshire.GriefPrevention.DataStore.getMessage(DataStore.java:1754) ~[?:?]
23.06 12:14:34 [Server] INFO at me.ryanhamshire.GriefPrevention.Claim.allowAccess(Claim.java:512) ~[?:?]
23.06 12:14:34 [Server] INFO at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerTeleport(PlayerEventHandler.java:1082) ~[?:?]
23.06 12:14:34 [Server] INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-354]
23.06 12:14:34 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-354]
23.06 12:14:34 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-354]
23.06 12:14:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-354]
23.06 12:14:34 [Server] INFO at net.minecraft.server.v1_15_R1.EntityEnderPearl.a(EntityEnderPearl.java:81) ~[patched_1.15.2.jar:git-Paper-354]
23.06 12:14:34 [Server] INFO at net.minecraft.server.v1_15_R1.EntityProjectile.tick(EntityProjectile.java:115) ~[patched_1.15.2.jar:git-Paper-354]
23.06 12:14:34 [Server] INFO at net.minecraft.server.v1_15_R1.EntityEnderPearl.tick(EntityEnderPearl.java:121) ~[patched_1.15.2.jar:git-Paper-354]
23.06 12:14:34 [Server] INFO at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:807) ~[patched_1.15.2.jar:git-Paper-354]
23.06 12:14:34 [Server] INFO at net.minecraft.server.v1_15_R1.World.a(World.java:879) ~[patched_1.15.2.jar:git-Paper-354]
23.06 12:14:34 [Server] INFO at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:532) ~[patched_1.15.2.jar:git-Paper-354]
23.06 12:14:34 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1327) ~[patched_1.15.2.jar:git-Paper-354]
23.06 12:14:34 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-354]
23.06 12:14:34 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-354]
23.06 12:14:34 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-354]
23.06 12:14:34 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment]
Invalid ticket format (lacks necessary information to determine problem). Please fill out the template you deleted.
