### ISSUE TITLE
Distance cannot be calculated in different worlds

### ISSUE THREAD

**Issue by justEli** [GriefPrevention/GriefPrevention#915]
### What happened:
Distance cannot be calculated in different worlds

### Steps to reproduce:
Do /trapped and teleport to another world.

### Server and GriefPrevention version:
Paste of `/version`: Paper-126
Paste of `/version GriefPrevention`: 16.13.0

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.
[13:47:48 WARN]: [GriefPrevention] Task #2686125 for GriefPrevention v16.13.0-253206a generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world_the_end and world
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.1.jar:git-Paper-126]
        at org.bukkit.Location.distance(Location.java:493) ~[patched_1.16.1.jar:git-Paper-126]
        at me.ryanhamshire.GriefPrevention.PlayerRescueTask.run(PlayerRescueTask.java:56) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-126]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-126]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-126]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-126]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-126]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-126]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-126]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

```
Fix:

Line 56
in class PlayerRescueTask

from
```
        if (player.getLocation().distance(this.location) > 3)
        {
            GriefPrevention.sendMessage(player, TextMode.Err, Messages.RescueAbortedMoved);
            return;
        }
```
to
```
        if (this.location.getWorld() != player.getLocation().getWorld() || player.getLocation().distance(this.location) > 3)
        {
            GriefPrevention.sendMessage(player, TextMode.Err, Messages.RescueAbortedMoved);
            return;
        }
```

I can do a pull request when I have the time.

**Comment by RoboMWM** [comment]
Or cancel if a teleport has occurred, but that's more lines. I almost don't want to put in this check for a harmless edge case, but whatever, guess it makes sense to do this check whenever #distance is called...
