### ISSUE TITLE
Overstack flow when using CoreProtect's inspect feature

### ISSUE THREAD

**Issue by HyplexMC** [GriefPrevention/GriefPrevention#974]
### What happened:
So when i do the `/co i` command it sends thousands of error's in the console and kills the server

### What was expected:
for the server to not be killed

### Steps to reproduce:
1. Step 1. Log into the server
2. Step 2. perform /co i
3. Step 3. Click (left or right) a block or place a block depending on with inspect you want to do
4. Kills the server instantly

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`:  PaperMC #135 for 1.16.1
Paste of `/version GriefPrevention`: 16.14.0

### Stack trace/error or server log
```[16:00:45] [Netty Epoll Server IO #3/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[16:00:47] [Netty Epoll Server IO #3/WARN]: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
[16:00:45] [Netty Epoll Server IO #3/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[16:00:47] [Netty Epoll Server IO #3/WARN]: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[16:00:45] [Netty Epoll Server IO #3/WARN]: 	at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[16:00:47] [Netty Epoll Server IO #3/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[16:00:45] [Netty Epoll Server IO #3/WARN]: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[16:00:47] [Netty Epoll Server IO #3/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[16:00:45] [Netty Epoll Server IO #3/WARN]: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
[16:00:47] [Netty Epoll Server IO #3/WARN]: 	at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)```
```
### GriefPrevention config.yml

```
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_the_end: Disabled
      world: Survival
      world_nether: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 50
    Max Accrued Claim Blocks:
      Default: 10000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: -1
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: false
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 0
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 5
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa;/hub
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: false
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: true
  LimitTreeGrowth: false
  CheckPistonMovement: true
  LimitPistonsToLandClaims: false
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: false
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 2
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

```

### Plugin list (if applicable):
AntiCreeper, AntiXrayHeuristics, BKCommonLib, Clans, ClansChestAddon, ClansKillAddon, ClansRenameAddon, ClansShowAddon, CMI, CMIPaperLib, CoreProtect, DeluxeMenus, DiscordSRV, DiscordSRV-Staff-Chat, GriefPrevention, HeadDatabase*, Holograms, LightCleaner, LuckPerms, Multiverse-Core, PlaceholderAPI, PlayerReport, PluginLibrary, ProtocolLib, Quests, Rankup, ServerListPlus*, SimpleVoteListener*, SpecializedCrates, Statz, Vault, Votifier, WorldEdit, WorldGuard

### Debugging steps attempted

- [x] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment]
Imma assume you closed this cuz this wasn't a GP issue after all? Or what.

**Comment by HyplexMC** [comment]
No GP was the issue but i solved it by removing this plugin and downloading and purchasing GriefDefender

**Comment by RoboMWM** [comment]
…
I do not think GP is the issue here - I use CoreProtect and don't have issues, unless CoreProtect introduced a new bug in one of the updates. Either way GP wouldn't be the cause, but who knows since your stacktrace was incomplete.

**Comment by TerranTitan01** [comment]
GP is the issue I tested every plugin I use alone with coreprotect and GP is the only one that caused issues, and I’ve already talked with the devs of CoreProtect and they have clearly shown that the issue is not with CoreProtect and that stack trace I put in there is repeated over and over thousands of times, would you like me to post it? I think not it wouldn’t fit so I just took a small part of it.

**Comment by RoboMWM** [comment]
Yes... it's an overflow so it makes sense why it's large but the whole thing is needed to identify the issue.

**Comment by RoboMWM** [comment]
The portion included here is useless as it's pointing to gson stuff, which is a library and not part of the plugin itself.

**Comment by TerranTitan01** [comment]
Honestly no offense but I am really happy with GD so I don’t wish to continue here

**Comment by RoboMWM** [comment]
… Would be nice to know what the issue was so I could fix it (if it really is caused by GP), but ok I guess.

**Comment by TerranTitan01** [comment]
It’s 1:05am I’ll send the full stack later
