### ISSUE TITLE
Could not pass event PlayerInteractEvent to GriefPrevention v16.14.0

### ISSUE THREAD

**Issue by mm203** [GriefPrevention/GriefPrevention#978]
### What happened:
_Land Claims function not working

### What was expected:
_Ability to make land claims using a golden shovel and see previous claims with a stick

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Right click with either golden shovel or stick on any elevation
2. Look at console to see error

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 16.14.0
Paste of `/version GriefPrevention`: 

### Stack trace/error or server log

```
[12:39:30] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to GriefPrevention v16.14.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:478) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:444) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1278) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_16_R2.tag.CraftBlockTag.isTagged(CraftBlockTag.java:20) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.craftbukkit.v1_16_R2.tag.CraftBlockTag.isTagged(CraftBlockTag.java:1) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerInteract(PlayerEventHandler.java:1767) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	... 20 more
[12:39:30] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to GriefPrevention v16.14.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:478) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:444) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1278) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_16_R2.tag.CraftBlockTag.isTagged(CraftBlockTag.java:20) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.craftbukkit.v1_16_R2.tag.CraftBlockTag.isTagged(CraftBlockTag.java:1) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerInteract(PlayerEventHandler.java:1767) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot_1.16.2.jar:git-Spigot-379750e-9c9fb59]
	... 20 more

**(Info coming straight from Log)**
```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_the_end: Disabled
      world_nether: Disabled
      world: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 2000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  CheckPistonMovement: true
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

```

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment]
Besides missing stuff in the template, it sounds like you have some custom blocks that aren't tagged or something. Highly likely this is not a GP issue - test without other plugins.

**Comment by Jikoo** [comment]
This is more of a CB issue - when the given material is [converted into a block by the tag](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/tag/CraftBlockTag.java?at=9c9fb593f5e1dfb1f44661587d038c4a109c68a0#20), the result is null. Since the given material was not null, one expects it to be handled gracefully by Spigot, particularly since Bukkit doesn't expose the concept of block-specific material tags.

Presumably, either a plugin is firing a PlayerInteractEvent for an air block or CB has changed (air interactions have a null block, not a block that is air), because otherwise the block's material has to be a block. If you could fill out the rest of the information you're missing from the template that would be helpful.

While it didn't affect the readability of this particular stack trace, when you see Multicraft skipping lines during an error you should actually find it in the logs instead of copying it out of console - it often cuts off the actual source.

**Comment by mm203** [comment]
Updated the information after removing a few possible plugins that could have caused the issue.

**Comment by mm203** [comment]
These are the current plugins running:KISS-Spawn, dynmap KISS-back, GriefPrevention, dynmap-mobs

Do you think any of these could be causing the issue?

**Comment by Jikoo** [comment]
Can guarantee you it's a plugin based on the information given, cannot reproduce on 1.16.2 git-Spigot-d65430a-bad55db running GP 16.14.0-7999da4

GP could probably handle odd blocks being passed a little more gracefully, but it would be a good idea for you to isolate the plugin causing unexpected interaction behavior and find out why they're doing that. Based on name alone SimpleMechanics and GiveMeArms both sound like things that might alter interaction.

**Comment by Jikoo** [comment]
Actually this is 100% a Spigot issue, they already patched it nearly 2 weeks ago. You're ignoring the outdated build warning and everything.

**Comment by Jikoo** [comment]
Oh, not this exact issue actually. My bad, [Spigot-6061](https://hub.spigotmc.org/jira/browse/SPIGOT-6061) is very similar to this. Still more of a Spigot issue, and your server is still very outdated.

**Comment by mm203** [comment]
I completely wiped the previous spigot update and reinstalled it and it seems to have fixed the issue.

**Comment by RoboMWM** [comment]
sometimes I wonder if a plugin that reads stacktraces would be useful or not.

**Comment by mm203** [comment]
Do you know of one in particular?

**Comment by Jikoo** [comment]
As far as I am aware there isn't currently a plugin that makes it clearer what the source of a stack trace is to people who aren't used to reading them, I think that was more theoretical.

Glad to hear updating Spigot worked, thanks for keeping us posted.
